import { createHash } from "node:crypto";
import {
  lstat,
  mkdir,
  readdir,
  readFile,
  realpath,
  rename,
  rm,
  stat,
  writeFile,
} from "node:fs/promises";
import { homedir } from "node:os";
import { basename, dirname, join, relative, resolve, sep } from "node:path";
import { z } from "zod";
import { commandDefToModule } from "../command-source.ts";
import { assertValid } from "../define.ts";
import type { CommandDef } from "../types.ts";

const MAX_EXPORT_BYTES = 32 * 1024 * 1024;
const MAX_PORTABLE_TEXT_LENGTH = 8 * 1024;
const GENERATED_HEADER = [
  "// Generated by `polycast capture --from raycast-snippets`.",
  "// The source export stays outside Git. Regenerate this file instead of editing it.",
] as const;
const GENERATED_MARKER = GENERATED_HEADER[0];
const REPORT_FILENAME = "capture-report.json";
const REPORT_GENERATOR = "polycast capture --from raycast-snippets";

const raycastSnippetSchema = z
  .object({
    name: z.string(),
    text: z.string(),
    keyword: z.string().optional(),
    tags: z.array(z.string()).optional(),
  })
  .passthrough();

type RaycastSnippet = z.infer<typeof raycastSnippetSchema>;

export type RaycastSnippetRejectionCode =
  | "invalid-entry"
  | "empty-name"
  | "empty-text"
  | "blank-keyword"
  | "credential-like"
  | "personal-data"
  | "dynamic-placeholder"
  | "machine-specific"
  | "unsafe-operation"
  | "control-character"
  | "unicode-format-character"
  | "oversized"
  | "keyword-collision"
  | "id-collision";

export type RaycastSnippetLossCode = "name-trimmed" | "tags-omitted" | "unknown-fields-omitted";

interface ParsedSnippet {
  readonly sourceIndex: number;
  readonly snippet: RaycastSnippet;
  readonly losses: readonly RaycastSnippetLossCode[];
}

interface AcceptedSnippet extends ParsedSnippet {
  readonly command: CommandDef;
}

interface RejectedSnippet {
  readonly sourceIndex: number;
  readonly reason: RaycastSnippetRejectionCode;
}

export interface RaycastSnippetCaptureReport {
  readonly schemaVersion: 1;
  readonly generatedBy: typeof REPORT_GENERATOR;
  readonly sourceSha256: string;
  readonly sourceEntries: number;
  readonly accepted: readonly {
    readonly sourceIndex: number;
    readonly id: string;
    readonly losses: readonly RaycastSnippetLossCode[];
  }[];
  readonly rejected: readonly RejectedSnippet[];
}

export interface RaycastSnippetCapturePlan {
  readonly sourcePath: string;
  readonly sourceSha256: string;
  readonly sourceEntries: number;
  readonly accepted: number;
  readonly rejected: number;
  readonly rejectionCounts: Readonly<Partial<Record<RaycastSnippetRejectionCode, number>>>;
  readonly lossCounts: Readonly<Partial<Record<RaycastSnippetLossCode, number>>>;
  readonly outputDir: string;
  readonly create: number;
  readonly update: number;
  readonly remove: number;
  readonly unchanged: number;
  readonly reportChanged: boolean;
  readonly written: boolean;
}

export interface CaptureRaycastSnippetsOptions {
  readonly input?: string;
  readonly outputDir?: string;
  readonly write?: boolean;
  readonly searchDirs?: readonly string[];
}

export class RaycastSnippetCaptureError extends Error {
  constructor(
    message: string,
    readonly code: string,
  ) {
    super(message);
    this.name = "RaycastSnippetCaptureError";
  }
}

function sha256Text(value: string): string {
  return createHash("sha256").update(value).digest("hex");
}

function sha256Bytes(value: Uint8Array): string {
  return createHash("sha256").update(value).digest("hex");
}

function slugify(value: string): string {
  const slug = value
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 48)
    .replace(/-+$/g, "");
  return slug || "snippet";
}

function commandId(snippet: RaycastSnippet): string {
  const fingerprint = sha256Text(
    `${snippet.name.trim()}\0${snippet.keyword ?? ""}\0${snippet.text}`,
  ).slice(0, 10);
  return `raycast-snippet-${slugify(snippet.name)}-${fingerprint}`;
}

function commandFor(snippet: RaycastSnippet): CommandDef {
  const command: CommandDef = {
    id: commandId(snippet),
    title: snippet.name.trim(),
    description: "Static text captured from a Raycast snippet export.",
    modality: "none",
    body: {
      lang: "node",
      source: `process.stdout.write(${JSON.stringify(snippet.text)});`,
    },
    targets: ["raycast-snippet"],
    x: {
      raycast: {
        snippet: {
          text: snippet.text,
          ...(snippet.keyword ? { keyword: snippet.keyword } : {}),
        },
      },
    },
    author: "polycast capture",
  };
  assertValid(command);
  return command;
}

function hasControlCharacter(value: string): boolean {
  return /[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/u.test(value);
}

function hasUnicodeFormatCharacter(value: string): boolean {
  return /\p{Cf}/u.test(value);
}

function shannonEntropy(value: string): number {
  const frequencies = new Map<string, number>();
  for (const char of value) frequencies.set(char, (frequencies.get(char) ?? 0) + 1);
  let entropy = 0;
  for (const count of frequencies.values()) {
    const probability = count / value.length;
    entropy -= probability * Math.log2(probability);
  }
  return entropy;
}

function hasHighEntropyToken(value: string): boolean {
  for (const match of value.matchAll(/[A-Za-z0-9+/_=-]{40,256}/g)) {
    const token = match[0];
    const classes = [/[a-z]/, /[A-Z]/, /\d/, /[+/_=-]/].filter((pattern) =>
      pattern.test(token),
    ).length;
    if (classes >= 3 && shannonEntropy(token) >= 4.2) return true;
  }
  return false;
}

function hasShortSingleTokenPasswordShape(value: string): boolean {
  const token = value.trim();
  if (token.length < 8 || token.length > 39 || /\s/u.test(token)) return false;
  if (!/^[\x21-\x7E]+$/u.test(token)) return false;
  return [/[a-z]/, /[A-Z]/, /\d/, /[^A-Za-z0-9]/].every((pattern) => pattern.test(token));
}

function containsCredential(value: string): boolean {
  const knownPatterns = [
    /-----BEGIN (?:RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----/i,
    /\bgithub_pat_[A-Za-z0-9_]{20,}\b/,
    /\bgh[pousr]_[A-Za-z0-9]{20,}\b/,
    /\bsk-(?:proj-|svcacct-)?[A-Za-z0-9_-]{20,}\b/,
    /\bAKIA[0-9A-Z]{16}\b/,
    /\bxox[baprs]-[A-Za-z0-9-]{10,}\b/,
    /\bAIza[0-9A-Za-z_-]{30,}\b/,
    /\beyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\b/,
    /authorization\s*:\s*(?:bearer|basic)\s+\S+/i,
    /[a-z][a-z0-9+.-]*:\/\/[^/\s:@]+:[^/\s@]+@/i,
    /(?:password|passwd|secret|token|api[_-]?key|private[_-]?key|client[_-]?secret)\s*["']?\s*[:=]\s*["']?(?!\$\{|\$[A-Z_]+\b|\{\{|<[^>]+>|YOUR_|REPLACE|EXAMPLE)[^\s"'`]{8,}/i,
  ];
  return knownPatterns.some((pattern) => pattern.test(value)) || hasHighEntropyToken(value);
}

function namesCredentialMaterial(value: string): boolean {
  return /\b(?:1password|passwords?|passwd|credentials?|private[_ -]?keys?|secret[_ -]?keys?|access[_ -]?tokens?|auth[_ -]?tokens?|api[_ -]?keys?|setup[_ -]?tokens?|unlock[_ -]?keychain)\b|\.ssh\/id_|\bid_(?:rsa|ed25519|ecdsa)\b/i.test(
    value,
  );
}

function containsPersonalEmail(value: string): boolean {
  for (const match of value.matchAll(/[A-Z0-9._%+-]+@([A-Z0-9.-]+\.[A-Z]{2,})/gi)) {
    const domain = match[1]?.toLowerCase();
    if (domain && !["example.com", "example.org", "example.net"].includes(domain)) return true;
  }
  return false;
}

function luhnValid(digits: string): boolean {
  let sum = 0;
  let double = false;
  for (let index = digits.length - 1; index >= 0; index--) {
    let digit = Number(digits.charAt(index));
    if (double) {
      digit *= 2;
      if (digit > 9) digit -= 9;
    }
    sum += digit;
    double = !double;
  }
  return sum % 10 === 0;
}

function containsPaymentCard(value: string): boolean {
  for (const match of value.matchAll(/(?:\d[ -]?){13,19}/g)) {
    const digits = match[0].replace(/\D/g, "");
    if (digits.length >= 13 && digits.length <= 19 && luhnValid(digits)) return true;
  }
  return false;
}

function containsPersonalData(value: string): boolean {
  return (
    containsPersonalEmail(value) ||
    /\b\d{3}-\d{2}-\d{4}\b/.test(value) ||
    /(?:\+?1[ .-]?)?(?:\(\d{3}\)|\d{3})[ .-]\d{3}[ .-]\d{4}\b/.test(value) ||
    /\b(?:home|mailing|street) address\b|\bsocial security\b|\bpassport number\b/i.test(value) ||
    /\b\d{1,6}\s+[A-Z0-9.'-]+(?:\s+[A-Z0-9.'-]+){0,4}\s+(?:st(?:reet)?|ave(?:nue)?|rd|road|blvd|boulevard|ln|lane|dr|drive|ct|court|way|pkwy|parkway)\b/i.test(
      value,
    ) ||
    containsPaymentCard(value)
  );
}

function containsDynamicPlaceholder(value: string): boolean {
  return /\{(?:clipboard|snippet|cursor|date|time|datetime|day|uuid|selection|argument|calculator|browser-tab)(?:\s|\||\})/i.test(
    value,
  );
}

function containsMachineSpecificReference(value: string): boolean {
  return (
    /\/(?:users|home)\//i.test(value) ||
    /\b[A-Z]:\\Users\\[^\\\s]+\\/i.test(value) ||
    /\b(?:tailscale|magicdns)\b|\.ts\.net\b/i.test(value) ||
    /\b(?:\d{1,3}\.){3}\d{1,3}\b/.test(value) ||
    /\b(?:[0-9A-F]{2}:){5}[0-9A-F]{2}\b/i.test(value) ||
    /\b[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}\b/i.test(value) ||
    /(?:^|[\s"'`])~\/\.ssh\//m.test(value) ||
    /\b[^/\s]+\.(?:local|internal)\b/i.test(value) ||
    /https?:\/\/(?:localhost|127\.0\.0\.1|10\.\d+\.\d+\.\d+|192\.168\.\d+\.\d+|172\.(?:1[6-9]|2\d|3[01])\.\d+\.\d+|[^/\s]+\.(?:local|internal))(?:[/:]|$)/i.test(
      value,
    )
  );
}

function containsUnsafeOperation(value: string): boolean {
  return (
    /\brm\s+-[^\n]*r[^\n]*f|\brm\s+-[^\n]*f[^\n]*r/i.test(value) ||
    /\bgit\s+(?:reset\s+--hard|clean\s+-[^\s]*f|checkout\s+--\s+\.|restore\s+\.)/i.test(value) ||
    /\b(?:pkill|killall|mkfs)\b|\bdd\s+if=/i.test(value) ||
    /\bchmod\s+(?:-R\s+)?777\b/i.test(value) ||
    /\bcurl\b[^\n|]*\|\s*(?:ba|z|fi)?sh\b/i.test(value) ||
    /--dangerously-skip-permissions\b|--yolo\b/i.test(value)
  );
}

function rejectionFor(snippet: RaycastSnippet): RaycastSnippetRejectionCode | undefined {
  if (!snippet.name.trim()) return "empty-name";
  if (!snippet.text.trim()) return "empty-text";
  if (snippet.keyword !== undefined && !snippet.keyword.trim()) return "blank-keyword";
  if (snippet.text.length > MAX_PORTABLE_TEXT_LENGTH) return "oversized";
  const inspected = `${snippet.name}\n${snippet.text}\n${snippet.keyword ?? ""}`;
  if (hasControlCharacter(inspected)) return "control-character";
  if (hasUnicodeFormatCharacter(inspected)) return "unicode-format-character";
  if (
    containsCredential(inspected) ||
    hasShortSingleTokenPasswordShape(snippet.text) ||
    namesCredentialMaterial(inspected)
  ) {
    return "credential-like";
  }
  if (containsPersonalData(inspected)) return "personal-data";
  if (containsDynamicPlaceholder(snippet.text)) return "dynamic-placeholder";
  if (containsMachineSpecificReference(inspected)) return "machine-specific";
  if (containsUnsafeOperation(snippet.text)) return "unsafe-operation";
  return undefined;
}

function countBy<T extends string>(
  values: readonly T[],
  all: readonly T[],
): Partial<Record<T, number>> {
  const counts: Partial<Record<T, number>> = {};
  for (const value of all) counts[value] = 0;
  for (const value of values) counts[value] = (counts[value] ?? 0) + 1;
  return counts;
}

const ALL_REJECTION_CODES = [
  "invalid-entry",
  "empty-name",
  "empty-text",
  "blank-keyword",
  "credential-like",
  "personal-data",
  "dynamic-placeholder",
  "machine-specific",
  "unsafe-operation",
  "control-character",
  "unicode-format-character",
  "oversized",
  "keyword-collision",
  "id-collision",
] as const satisfies readonly RaycastSnippetRejectionCode[];

const ALL_LOSS_CODES = [
  "name-trimmed",
  "tags-omitted",
  "unknown-fields-omitted",
] as const satisfies readonly RaycastSnippetLossCode[];

function parseExport(raw: string): {
  readonly sourceEntries: number;
  readonly parsed: readonly ParsedSnippet[];
  readonly rejected: readonly RejectedSnippet[];
} {
  let input: unknown;
  try {
    input = JSON.parse(raw);
  } catch {
    throw new RaycastSnippetCaptureError(
      "Raycast snippet export is not valid JSON",
      "INVALID_JSON",
    );
  }
  if (!Array.isArray(input)) {
    throw new RaycastSnippetCaptureError(
      "Raycast snippet export must be a JSON array",
      "INVALID_ROOT",
    );
  }

  const parsed: ParsedSnippet[] = [];
  const rejected: RejectedSnippet[] = [];
  for (const [sourceIndex, item] of input.entries()) {
    const result = raycastSnippetSchema.safeParse(item);
    if (!result.success) {
      rejected.push({ sourceIndex, reason: "invalid-entry" });
      continue;
    }
    const knownKeys = new Set(["name", "text", "keyword", "tags"]);
    const losses: RaycastSnippetLossCode[] = [];
    if (result.data.name !== result.data.name.trim()) losses.push("name-trimmed");
    if (result.data.tags?.length) losses.push("tags-omitted");
    if (Object.keys(result.data).some((key) => !knownKeys.has(key))) {
      losses.push("unknown-fields-omitted");
    }
    const reason = rejectionFor(result.data);
    if (reason) rejected.push({ sourceIndex, reason });
    else parsed.push({ sourceIndex, snippet: result.data, losses });
  }
  return { sourceEntries: input.length, parsed, rejected };
}

function resolveConflicts(
  parsed: readonly ParsedSnippet[],
  initialRejected: readonly RejectedSnippet[],
): {
  readonly accepted: readonly AcceptedSnippet[];
  readonly rejected: readonly RejectedSnippet[];
} {
  const rejected = [...initialRejected];
  const collidedIndexes = new Set<number>();
  const keywords = new Map<string, number[]>();
  for (const entry of parsed) {
    if (!entry.snippet.keyword) continue;
    const indexes = keywords.get(entry.snippet.keyword) ?? [];
    indexes.push(entry.sourceIndex);
    keywords.set(entry.snippet.keyword, indexes);
  }
  for (const indexes of keywords.values()) {
    if (indexes.length < 2) continue;
    for (const sourceIndex of indexes) {
      collidedIndexes.add(sourceIndex);
      rejected.push({ sourceIndex, reason: "keyword-collision" });
    }
  }

  const candidates = parsed
    .filter((entry) => !collidedIndexes.has(entry.sourceIndex))
    .map((entry) => ({ ...entry, command: commandFor(entry.snippet) }));
  const ids = new Map<string, number[]>();
  for (const entry of candidates) {
    const indexes = ids.get(entry.command.id) ?? [];
    indexes.push(entry.sourceIndex);
    ids.set(entry.command.id, indexes);
  }
  for (const indexes of ids.values()) {
    if (indexes.length < 2) continue;
    for (const sourceIndex of indexes) {
      collidedIndexes.add(sourceIndex);
      rejected.push({ sourceIndex, reason: "id-collision" });
    }
  }

  return {
    accepted: candidates
      .filter((entry) => !collidedIndexes.has(entry.sourceIndex))
      .sort((a, b) => a.command.id.localeCompare(b.command.id)),
    rejected: rejected.sort((a, b) => a.sourceIndex - b.sourceIndex),
  };
}

async function physicalPath(path: string): Promise<string> {
  try {
    return await realpath(path);
  } catch (error) {
    if (!(error instanceof Error && "code" in error && error.code === "ENOENT")) throw error;
    const parent = dirname(path);
    if (parent === path) throw error;
    return join(await physicalPath(parent), basename(path));
  }
}

async function moduleImportPath(outputDir: string): Promise<string> {
  const physicalOutput = await physicalPath(outputDir);
  const physicalDefinition = await physicalPath(resolve("src/define.ts"));
  const path = relative(physicalOutput, physicalDefinition).split(sep).join("/");
  return path.startsWith(".") ? path : `./${path}`;
}

function reportFor(
  sourceSha256: string,
  sourceEntries: number,
  accepted: readonly AcceptedSnippet[],
  rejected: readonly RejectedSnippet[],
): RaycastSnippetCaptureReport {
  return {
    schemaVersion: 1,
    generatedBy: REPORT_GENERATOR,
    sourceSha256,
    sourceEntries,
    accepted: accepted.map((entry) => ({
      sourceIndex: entry.sourceIndex,
      id: entry.command.id,
      losses: entry.losses,
    })),
    rejected,
  };
}

interface OwnedOutput {
  readonly files: ReadonlyMap<string, string>;
  readonly staleTemporaries: readonly string[];
}

function isAtomicTemporary(name: string): boolean {
  const match = /^(.*)\.polycast-tmp-[1-9]\d*$/u.exec(name);
  const target = match?.[1];
  if (!target) return false;
  return (
    target === REPORT_FILENAME ||
    /^raycast-snippet-[a-z0-9]+(?:-[a-z0-9]+)*-[0-9a-f]{10}\.ts$/u.test(target)
  );
}

async function readOwnedOutput(outputDir: string): Promise<OwnedOutput> {
  const files = new Map<string, string>();
  const staleTemporaries: string[] = [];
  const entries = await readdir(outputDir, { withFileTypes: true }).catch((error) => {
    if (error instanceof Error && "code" in error && error.code === "ENOENT") return [];
    throw error;
  });
  for (const entry of entries) {
    if (entry.isFile() && isAtomicTemporary(entry.name)) {
      staleTemporaries.push(entry.name);
      continue;
    }
    if (!entry.isFile()) {
      throw new RaycastSnippetCaptureError(
        `refusing to write: ${join(outputDir, entry.name)} is not a generated file`,
        "FOREIGN_OUTPUT",
      );
    }
    const path = join(outputDir, entry.name);
    const contents = await readFile(path, "utf8");
    if (entry.name.endsWith(".ts")) {
      if (!contents.startsWith(GENERATED_MARKER)) {
        throw new RaycastSnippetCaptureError(
          `refusing to overwrite non-generated file: ${path}`,
          "FOREIGN_OUTPUT",
        );
      }
    } else if (entry.name === REPORT_FILENAME) {
      let report: unknown;
      try {
        report = JSON.parse(contents);
      } catch {
        report = undefined;
      }
      if (
        typeof report !== "object" ||
        report === null ||
        !("generatedBy" in report) ||
        report.generatedBy !== REPORT_GENERATOR
      ) {
        throw new RaycastSnippetCaptureError(
          `refusing to overwrite non-generated file: ${path}`,
          "FOREIGN_OUTPUT",
        );
      }
    } else {
      throw new RaycastSnippetCaptureError(
        `refusing to write alongside non-generated file: ${path}`,
        "FOREIGN_OUTPUT",
      );
    }
    files.set(entry.name, contents);
  }
  return { files, staleTemporaries };
}

async function writeAtomically(path: string, contents: string): Promise<void> {
  const temporary = `${path}.polycast-tmp-${process.pid}`;
  await writeFile(temporary, contents, { mode: 0o644 });
  await rename(temporary, path);
}

export async function discoverLatestRaycastSnippetExport(
  searchDirs?: readonly string[],
): Promise<string> {
  const configured = process.env.POLYCAST_RAYCAST_SNIPPET_EXPORT_DIR;
  const defaultDirs = [
    ...(configured ? [configured] : []),
    join(homedir(), ".dotfiles", "raycast", "snippets"),
    join(homedir(), "Downloads"),
  ];
  const directories = searchDirs ?? defaultDirs;
  const candidates: { readonly path: string; readonly modifiedMs: number }[] = [];
  for (const directory of directories) {
    const entries = await readdir(directory, { withFileTypes: true }).catch(() => []);
    for (const entry of entries) {
      if (!entry.isFile() || !entry.name.toLowerCase().endsWith(".json")) continue;
      if (basename(directory) === "Downloads" && !/snippet/i.test(entry.name)) continue;
      const path = join(directory, entry.name);
      const info = await stat(path);
      candidates.push({ path, modifiedMs: info.mtimeMs });
    }
  }
  candidates.sort((a, b) => b.modifiedMs - a.modifiedMs || a.path.localeCompare(b.path));
  const latest = candidates[0];
  if (!latest) {
    throw new RaycastSnippetCaptureError(
      `no Raycast snippets JSON export found in: ${directories.map((directory) => resolve(directory)).join(", ")}`,
      "EXPORT_NOT_FOUND",
    );
  }
  return resolve(latest.path);
}

export async function captureRaycastSnippets(
  options: CaptureRaycastSnippetsOptions = {},
): Promise<RaycastSnippetCapturePlan> {
  const sourcePath = options.input
    ? resolve(options.input)
    : await discoverLatestRaycastSnippetExport(options.searchDirs);
  const sourceInfo = await lstat(sourcePath);
  if (!sourceInfo.isFile() || sourceInfo.isSymbolicLink()) {
    throw new RaycastSnippetCaptureError(
      `Raycast snippet export must be a regular, non-symlink file: ${sourcePath}`,
      "UNSAFE_INPUT",
    );
  }
  if (sourceInfo.size > MAX_EXPORT_BYTES) {
    throw new RaycastSnippetCaptureError(
      `Raycast snippet export exceeds ${MAX_EXPORT_BYTES} bytes: ${sourcePath}`,
      "EXPORT_TOO_LARGE",
    );
  }

  const sourceBytes = await readFile(sourcePath);
  const sourceSha256 = sha256Bytes(sourceBytes);
  let raw: string;
  try {
    raw = new TextDecoder("utf-8", { fatal: true }).decode(sourceBytes);
  } catch {
    throw new RaycastSnippetCaptureError(
      "Raycast snippet export is not valid UTF-8",
      "INVALID_UTF8",
    );
  }
  const { sourceEntries, parsed, rejected: initialRejected } = parseExport(raw);
  const { accepted, rejected } = resolveConflicts(parsed, initialRejected);
  if (accepted.length === 0 && options.write) {
    throw new RaycastSnippetCaptureError(
      "refusing to write an empty capture; review the rejection summary first",
      "EMPTY_CAPTURE",
    );
  }

  const outputDir = resolve(options.outputDir ?? join("commands", "raycast-snippets"));
  const defineImport = await moduleImportPath(outputDir);
  const desired = new Map<string, string>();
  for (const entry of accepted) {
    desired.set(
      `${entry.command.id}.ts`,
      commandDefToModule(entry.command, { defineImport, header: GENERATED_HEADER }),
    );
  }
  const report = reportFor(sourceSha256, sourceEntries, accepted, rejected);
  desired.set(REPORT_FILENAME, `${JSON.stringify(report, null, 2)}\n`);

  const { files: existing, staleTemporaries } = await readOwnedOutput(outputDir);
  const create = [...desired].filter(([name]) => !existing.has(name)).length;
  const update = [...desired].filter(
    ([name, contents]) => existing.has(name) && existing.get(name) !== contents,
  ).length;
  const unchanged = [...desired].filter(
    ([name, contents]) => existing.get(name) === contents,
  ).length;
  const remove =
    [...existing].filter(([name]) => !desired.has(name)).length + staleTemporaries.length;
  const reportChanged = existing.get(REPORT_FILENAME) !== desired.get(REPORT_FILENAME);

  if (options.write) {
    await mkdir(outputDir, { recursive: true });
    for (const [name, contents] of desired) {
      if (existing.get(name) === contents) continue;
      await writeAtomically(join(outputDir, name), contents);
    }
    for (const [name] of existing) {
      if (!desired.has(name)) await rm(join(outputDir, name));
    }
    for (const name of staleTemporaries) {
      await rm(join(outputDir, name), { force: true });
    }
  }

  const rejectionCounts = countBy(
    rejected.map((entry) => entry.reason),
    ALL_REJECTION_CODES,
  );
  const lossCounts = countBy(
    accepted.flatMap((entry) => entry.losses),
    ALL_LOSS_CODES,
  );
  return {
    sourcePath,
    sourceSha256,
    sourceEntries,
    accepted: accepted.length,
    rejected: rejected.length,
    rejectionCounts,
    lossCounts,
    outputDir,
    create: create - (existing.has(REPORT_FILENAME) ? 0 : 1),
    update: update - (existing.has(REPORT_FILENAME) && reportChanged ? 1 : 0),
    remove,
    unchanged: unchanged - (existing.get(REPORT_FILENAME) === desired.get(REPORT_FILENAME) ? 1 : 0),
    reportChanged,
    written: options.write ?? false,
  };
}
