// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-tmux-move-all-windows-into-active-session-a729e39761",
  "title": "Tmux: Move all windows into active session",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"current_client=\\\"$(tmux display-message -p '#{client_name}')\\\"; current_sess=\\\"$(tmux display-message -p '#S')\\\"; current_win=\\\"$(tmux display-message -p '#I')\\\"; tmux list-windows -a -F '#{session_name} #{window_index}' | while read -r s w; do [[ \\\"$s\\\" == \\\"$current_sess\\\" && \\\"$w\\\" == \\\"$current_win\\\" ]] && continue; tmux move-window -s \\\"${s}:${w}\\\" -t \\\"${current_sess}\\\"; done\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "current_client=\"$(tmux display-message -p '#{client_name}')\"; current_sess=\"$(tmux display-message -p '#S')\"; current_win=\"$(tmux display-message -p '#I')\"; tmux list-windows -a -F '#{session_name} #{window_index}' | while read -r s w; do [[ \"$s\" == \"$current_sess\" && \"$w\" == \"$current_win\" ]] && continue; tmux move-window -s \"${s}:${w}\" -t \"${current_sess}\"; done"
      }
    }
  },
  "author": "polycast capture"
});
