// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-td-0-clean-out-td-board-short-99f5bcb1e3",
  "title": "td-0 - Clean out td board (short)",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"Reach td 0 on the current project: inspect the td board with td list/focus/status, group\\ntasks into epics with critical-path ordering, flag vague tasks for enrichment, verify review\\nitems have recorded approvals, output the execution order, then begin ce-work on the first unblocked task. Follow td-task-management and ce-lfg. Stop if already at td 0 or if 3+ tasks need clarification.\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "Reach td 0 on the current project: inspect the td board with td list/focus/status, group\ntasks into epics with critical-path ordering, flag vague tasks for enrichment, verify review\nitems have recorded approvals, output the execution order, then begin ce-work on the first unblocked task. Follow td-task-management and ce-lfg. Stop if already at td 0 or if 3+ tasks need clarification.",
        "keyword": ";td0s"
      }
    }
  },
  "author": "polycast capture"
});
