// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-review-and-test-code-changes-ai-42bae0c0df",
  "title": "Review and test code changes (AI)",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"# Review and test code changes\\n\\nEverything below assumes you are in the repo root directory, change there if needed before running.\\n\\nRUN:\\nmake install\\nsource .venv/bin/activate\\nmake check\\nmake test\\n\\nIf all tests pass, let's take a look at the implementation philosophy documents to ensure we are aligned with the project's design principles.\\n\\nREAD:\\n@ai_context/IMPLEMENTATION_PHILOSOPHY.md\\n@ai_context/MODULAR_DESIGN_PHILOSOPHY.md\\n\\nNow go and look at what code is currently changed since the last commit. Ultrathink and review each of those files more thoroughly and make sure they are aligned with the implementation philosophy documents. Follow the breadcrumbs in the files to their dependencies or files they are importing and make sure those are also aligned with the implementation philosophy documents.\\n\\nGive me a comprehensive report on how well the current code aligns with the implementation philosophy documents. If there are any discrepancies or areas for improvement, please outline them clearly with suggested changes or refactoring ideas.\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "# Review and test code changes\n\nEverything below assumes you are in the repo root directory, change there if needed before running.\n\nRUN:\nmake install\nsource .venv/bin/activate\nmake check\nmake test\n\nIf all tests pass, let's take a look at the implementation philosophy documents to ensure we are aligned with the project's design principles.\n\nREAD:\n@ai_context/IMPLEMENTATION_PHILOSOPHY.md\n@ai_context/MODULAR_DESIGN_PHILOSOPHY.md\n\nNow go and look at what code is currently changed since the last commit. Ultrathink and review each of those files more thoroughly and make sure they are aligned with the implementation philosophy documents. Follow the breadcrumbs in the files to their dependencies or files they are importing and make sure those are also aligned with the implementation philosophy documents.\n\nGive me a comprehensive report on how well the current code aligns with the implementation philosophy documents. If there are any discrepancies or areas for improvement, please outline them clearly with suggested changes or refactoring ideas."
      }
    }
  },
  "author": "polycast capture"
});
