// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-skill-grill-me-367423b968",
  "title": "Skill: Grill Me",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"---\\nname: grill-me\\ndescription: Interview the user relentlessly about a plan or design until reaching shared understanding, resolving each branch of the decision tree. Use when user wants to stress-test a plan, get grilled on their design, or mentions \\\"grill me\\\".\\n---\\n\\nInterview me relentlessly about every aspect of this plan until we reach a shared understanding. Walk down each branch of the design tree, resolving dependencies between decisions one-by-one. For each question, provide your recommended answer.\\n\\nAsk the questions one at a time.\\n\\nIf a question can be answered by exploring the codebase, explore the codebase instead.\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "---\nname: grill-me\ndescription: Interview the user relentlessly about a plan or design until reaching shared understanding, resolving each branch of the decision tree. Use when user wants to stress-test a plan, get grilled on their design, or mentions \"grill me\".\n---\n\nInterview me relentlessly about every aspect of this plan until we reach a shared understanding. Walk down each branch of the design tree, resolving dependencies between decisions one-by-one. For each question, provide your recommended answer.\n\nAsk the questions one at a time.\n\nIf a question can be answered by exploring the codebase, explore the codebase instead."
      }
    }
  },
  "author": "polycast capture"
});
