// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-rank-order-by-impact-ease-of-speed-implementatio-52e700ba40",
  "title": "Rank order by impact + ease of speed / implementation",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"Give each a 10 point rating (1-5 [impact] + 1-5 [ease/speed of implementation]). rank order with their final ratings\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "Give each a 10 point rating (1-5 [impact] + 1-5 [ease/speed of implementation]). rank order with their final ratings"
      }
    }
  },
  "author": "polycast capture"
});
