// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-ai-skill-improvements-75ec73bc5b",
  "title": "AI: skill improvements",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"Role: maintainer of this repo's agent-skill corpus. From recent project activity, recommend which SKILL.md files to create or enhance — every recommendation anchored to cited evidence. Do not edit files; output recommendations only.\\n\\nRead first:\\n- The last ~15 merged PRs and their review comments.\\n- Recurring signals: repeated review feedback, bugs that reappear, manual steps done more than once.\\nCross-check each idea against the existing skill catalog so you can label it [create] (nothing covers it) or [enhance] (a named existing skill is incomplete).\\n\\nOutput 3–6 items, ranked by impact, each exactly:\\n- [create|enhance] <skill-id> — one-line scope\\n- Evidence: PR #, review quote, or file:line (quote it, don't paraphrase)\\n- Change: the specific section or behavior to add/fix\\n- Why now: the recurring cost this removes\\n\\nRules:\\n- Every item MUST cite evidence from above. No item without a concrete reference.\\n- No generic advice (\\\"add tests\\\", \\\"improve docs\\\") unless tied to a named recurring failure.\\n- If support for a candidate is thin, mark it [speculative] — never invent evidence.\\n\\nDone when: each item names a real skill action, cites evidence, and states a specific change. Drop anything you can't ground.\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "Role: maintainer of this repo's agent-skill corpus. From recent project activity, recommend which SKILL.md files to create or enhance — every recommendation anchored to cited evidence. Do not edit files; output recommendations only.\n\nRead first:\n- The last ~15 merged PRs and their review comments.\n- Recurring signals: repeated review feedback, bugs that reappear, manual steps done more than once.\nCross-check each idea against the existing skill catalog so you can label it [create] (nothing covers it) or [enhance] (a named existing skill is incomplete).\n\nOutput 3–6 items, ranked by impact, each exactly:\n- [create|enhance] <skill-id> — one-line scope\n- Evidence: PR #, review quote, or file:line (quote it, don't paraphrase)\n- Change: the specific section or behavior to add/fix\n- Why now: the recurring cost this removes\n\nRules:\n- Every item MUST cite evidence from above. No item without a concrete reference.\n- No generic advice (\"add tests\", \"improve docs\") unless tied to a named recurring failure.\n- If support for a candidate is thin, mark it [speculative] — never invent evidence.\n\nDone when: each item names a real skill action, cites evidence, and states a specific change. Drop anything you can't ground."
      }
    }
  },
  "author": "polycast capture"
});
