// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-implement-and-use-your-best-judgement-9fe39f1a4d",
  "title": "Implement and use your best judgement.",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"Implement your plan. For any blockers, try using your best judgment first.\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "Implement your plan. For any blockers, try using your best judgment first.",
        "keyword": ";imp"
      }
    }
  },
  "author": "polycast capture"
});
