// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-proposal-title-public-relations-the-rundown-reta-f204f04ac8",
  "title": "Proposal Title - Public Relations - The Rundown (Retainer)",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"Public Relations - The Rundown (Retainer)\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "Public Relations - The Rundown (Retainer)",
        "keyword": "proposal;title;rundown"
      }
    }
  },
  "author": "polycast capture"
});
