// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-repomix-copy-to-clipboard-6983979afe",
  "title": "Repomix + Copy to Clipboard",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"repomix . | pbcopy\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "repomix . | pbcopy",
        "keyword": ";repomix:copy"
      }
    }
  },
  "author": "polycast capture"
});
