// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-use-your-best-judgement-03662e5058",
  "title": "use your best judgement",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"You pick / you choose. Use your best judgement based on what you know about our repo. If necessary spend some time researching the project, git history, documentation and code to inform your choice.\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "You pick / you choose. Use your best judgement based on what you know about our repo. If necessary spend some time researching the project, git history, documentation and code to inform your choice.",
        "keyword": "nou"
      }
    }
  },
  "author": "polycast capture"
});
