// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-tmux-session-info-c411aa9412",
  "title": "tmux session info",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"tmux display-message \\\"#{session_name} #{window_index} #{pane_index}\\\"\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "tmux display-message \"#{session_name} #{window_index} #{pane_index}\"",
        "keyword": "tmid;"
      }
    }
  },
  "author": "polycast capture"
});
