// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-glasses-of-disapproval-unicode-0791532dba",
  "title": "Glasses of Disapproval Unicode",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"(-■_■)\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "(-■_■)",
        "keyword": "!glasses-disapproval"
      }
    }
  },
  "author": "polycast capture"
});
