// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-compress-consolidate-documentation-7b005dfa63",
  "title": "Compress / Consolidate Documentation",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"You will be given a list of Claude code skills from GitHub. Your task is to clean up this list by removing duplicates and creating concise descriptions.\\n\\n<skills_list>\\n\\n\\n</skills_list>\\n\\nYour job is to:\\n1. **Deduplicate**: Identify and remove any duplicate skills in the list. Skills should be considered duplicates if they refer to the same core capability, even if worded differently.\\n2. **Compress and consolidate**: For each unique skill, create a clean entry consisting of:\\n   - A clear, concise name for the skill\\n   - A 2-3 sentence summary that captures the essence of what the skill does\\n\\nBefore providing your final answer, use the scratchpad below to work through the process:\\n\\n<scratchpad>\\nFirst, go through the skills list and identify potential duplicates by looking for skills that serve the same core function or purpose, even if described differently.\\n\\nThen, for each unique skill you identify, think about how to best name it and summarize its functionality in 2-3 clear sentences.\\n</scratchpad>\\n\\nPresent your final cleaned and consolidated skills list in the following format:\\n\\n**[Skill Name]**: [2-3 sentence description of what the skill does and its key capabilities]\\n\\nYour final output should contain only the deduplicated and consolidated skills list with no additional commentary or explanation.\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "You will be given a list of Claude code skills from GitHub. Your task is to clean up this list by removing duplicates and creating concise descriptions.\n\n<skills_list>\n\n\n</skills_list>\n\nYour job is to:\n1. **Deduplicate**: Identify and remove any duplicate skills in the list. Skills should be considered duplicates if they refer to the same core capability, even if worded differently.\n2. **Compress and consolidate**: For each unique skill, create a clean entry consisting of:\n   - A clear, concise name for the skill\n   - A 2-3 sentence summary that captures the essence of what the skill does\n\nBefore providing your final answer, use the scratchpad below to work through the process:\n\n<scratchpad>\nFirst, go through the skills list and identify potential duplicates by looking for skills that serve the same core function or purpose, even if described differently.\n\nThen, for each unique skill you identify, think about how to best name it and summarize its functionality in 2-3 clear sentences.\n</scratchpad>\n\nPresent your final cleaned and consolidated skills list in the following format:\n\n**[Skill Name]**: [2-3 sentence description of what the skill does and its key capabilities]\n\nYour final output should contain only the deduplicated and consolidated skills list with no additional commentary or explanation."
      }
    }
  },
  "author": "polycast capture"
});
