// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-mkmv-create-directory-and-move-file-into-it-7c390aa419",
  "title": "mkmv - Create directory and move file into it",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"mkmv \");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "mkmv ",
        "keyword": "mkmv"
      }
    }
  },
  "author": "polycast capture"
});
