// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-lenny-unicode-d7a35eb1f8",
  "title": "Lenny Unicode",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"( ͡° ͜ʖ ͡°)\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "( ͡° ͜ʖ ͡°)",
        "keyword": "!lenny"
      }
    }
  },
  "author": "polycast capture"
});
