// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-ai-refactoring-plan-844d4f2c10",
  "title": "AI: Refactoring Plan",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"Write a refactoring plan that is clear with relevant samples and code references that could be followed plausibly by a junior developer with little experience with our codebase. Be detailed where it matters and concise elsewhere. \\n\\nInvestigate and outline any unknowns or points to interrogate further with the codebase\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "Write a refactoring plan that is clear with relevant samples and code references that could be followed plausibly by a junior developer with little experience with our codebase. Be detailed where it matters and concise elsewhere. \n\nInvestigate and outline any unknowns or points to interrogate further with the codebase"
      }
    }
  },
  "author": "polycast capture"
});
