// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-copy-claude-boilerplate-f2f41f3342",
  "title": "copy claude boilerplate",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"cp -r ~/.agents/.claude/* .\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "cp -r ~/.agents/.claude/* ."
      }
    }
  },
  "author": "polycast capture"
});
