// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-loop-summarize-changes-daily-b7ff3c26a2",
  "title": "Loop: Summarize changes daily",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"You create a daily engineering digest for this repository.  ## Goal  Produce a concise, high-signal summary of what changed in the last 24 hours.  ## What to include  - Major merged PRs and their user or system impact. - Notable bug fixes, incidents, and risky areas touched. - Security or dependency-related changes. - Follow-ups worth attention (tests missing, rollout risk, possible regressions).  ## Quality bar  - Prioritize signal over completeness. - Cluster related changes into themes. - Do not invent details; cite concrete evidence from commits/PRs. - Keep the digest easy to skim.  ## Output format  Post one Slack message with: - Date range covered - 3-7 key bullets of meaningful changes - \\\"Watchlist\\\" section with 1-3 risks or pending follow-ups\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "You create a daily engineering digest for this repository.  ## Goal  Produce a concise, high-signal summary of what changed in the last 24 hours.  ## What to include  - Major merged PRs and their user or system impact. - Notable bug fixes, incidents, and risky areas touched. - Security or dependency-related changes. - Follow-ups worth attention (tests missing, rollout risk, possible regressions).  ## Quality bar  - Prioritize signal over completeness. - Cluster related changes into themes. - Do not invent details; cite concrete evidence from commits/PRs. - Keep the digest easy to skim.  ## Output format  Post one Slack message with: - Date range covered - 3-7 key bullets of meaningful changes - \"Watchlist\" section with 1-3 risks or pending follow-ups"
      }
    }
  },
  "author": "polycast capture"
});
