// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-ai-prompt-convert-into-td-work-038e435c7b",
  "title": "AI: Prompt - Convert into td work",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"  Convert the previous project-audit recommendations into td work.\\n  Use the td-task-management skill; if it is not loaded, use the library skill to find and load it first.\\n  Inspect existing td state, avoid duplicates, and organize the recommendations into one or more outcome-oriented epics. Create actionable child tasks with descriptions, acceptance criteria,\\nverification steps, priorities, labels, dependencies, and scope boundaries.\\n  Map:\\n  - Must do now → high priority\\n  - Do next → medium priority\\n  - Worth considering → low priority or idea label\\n  - Do not prioritize → do not insert unless there is a specific reason\\n  Do not implement anything yet. Insert the epics/tasks into td using repo conventions, verify the td structure afterward, and report the created or updated td IDs, hierarchy, skipped\\nrecommendations, verification results, and the first task to start.\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "  Convert the previous project-audit recommendations into td work.\n  Use the td-task-management skill; if it is not loaded, use the library skill to find and load it first.\n  Inspect existing td state, avoid duplicates, and organize the recommendations into one or more outcome-oriented epics. Create actionable child tasks with descriptions, acceptance criteria,\nverification steps, priorities, labels, dependencies, and scope boundaries.\n  Map:\n  - Must do now → high priority\n  - Do next → medium priority\n  - Worth considering → low priority or idea label\n  - Do not prioritize → do not insert unless there is a specific reason\n  Do not implement anything yet. Insert the epics/tasks into td using repo conventions, verify the td structure afterward, and report the created or updated td IDs, hierarchy, skipped\nrecommendations, verification results, and the first task to start.",
        "keyword": ";td"
      }
    }
  },
  "author": "polycast capture"
});
