// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-flipping-table-unicode-7c8b93b419",
  "title": "Flipping Table Unicode",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"(╯°□°)╯︵ ┻━┻\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "(╯°□°)╯︵ ┻━┻",
        "keyword": "!flipping-table"
      }
    }
  },
  "author": "polycast capture"
});
