// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-ptl-expand-please-take-a-look-f3adebc35e",
  "title": ";ptl - Expand - Please take a look...",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"Please take a look when you get the chance and let me know if you have any questions at all. \\n\\nI'm more than happy to walk you through everything in more detail.\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "Please take a look when you get the chance and let me know if you have any questions at all. \n\nI'm more than happy to walk you through everything in more detail.",
        "keyword": ";ptl"
      }
    }
  },
  "author": "polycast capture"
});
