// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-amplifier-create-scenario-d95e17dcef",
  "title": "Amplifier: Create scenario",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"I want you to look at the examples under @scenarios/ so we can make a new tool along those lines\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "I want you to look at the examples under @scenarios/ so we can make a new tool along those lines"
      }
    }
  },
  "author": "polycast capture"
});
