// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-email-subject-as-needed-podcasting-c61cd6cb41",
  "title": "Email - Subject (As Needed Podcasting)",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"Podcasting - Dallas Studios (as needed)\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "Podcasting - Dallas Studios (as needed)",
        "keyword": "proposal;title;asneeded"
      }
    }
  },
  "author": "polycast capture"
});
