// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-fresh-eyes-codebaze-review-optimized-20e5fb238b",
  "title": "Fresh Eyes codebaze review optimized",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"You are an expert software engineer and code reviewer.\\n\\nYour task is to review the provided codebase **with fresh eyes** and perform a thorough, critical audit.\\n\\n**Goal**\\nIdentify and document any issues, including but not limited to:\\n-  Sloppiness or poor code hygiene\\n-  Incomplete or abandoned thoughts\\n-  Logical errors or flawed assumptions\\n-  Bugs or potential bugs\\n-  Edge cases not handled\\n-  Confusing structure or naming\\n-  Inconsistencies in style or patterns\\n-  Missing error handling or validation\\n-  Performance or scalability concerns (where obvious)\\n-  Anything that could reasonably cause future confusion or failure\\n\\n**How to Review**\\n-  Read carefully and skeptically, as if onboarding to the project for the first time.\\n-  Assume no prior context beyond what is in the code.\\n-  Be explicit about *why* something is a problem or risk.\\n-  If something is ambiguous, call it out.\\n-  If something looks intentional but questionable, note that too.\\n\\n**Output Requirements**\\n-  Produce a **single Markdown file**.\\n-  Save it to: `docs/reviews/`\\n-  Filename format:  \\n  `{YYYY-MM-DD_HH-MM}_[short-descriptive-review-title].md`\\n-  Use clear Markdown structure, such as:\\n  - Overview / Summary\\n  - High-Priority Issues\\n  - Medium / Low-Proority Issues\\n  - Code Smells / Style Problems\\n  - Questions or Unclear Intent\\n  - Suggestions for Improvement\\n\\n**Tone**\\n-  Direct, precise, and constructive.\\n-  No fluff, no hedging.\\n-  Treat this as a professional internal code review.\\n\\nBegin once the full codebase is available.\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "You are an expert software engineer and code reviewer.\n\nYour task is to review the provided codebase **with fresh eyes** and perform a thorough, critical audit.\n\n**Goal**\nIdentify and document any issues, including but not limited to:\n-  Sloppiness or poor code hygiene\n-  Incomplete or abandoned thoughts\n-  Logical errors or flawed assumptions\n-  Bugs or potential bugs\n-  Edge cases not handled\n-  Confusing structure or naming\n-  Inconsistencies in style or patterns\n-  Missing error handling or validation\n-  Performance or scalability concerns (where obvious)\n-  Anything that could reasonably cause future confusion or failure\n\n**How to Review**\n-  Read carefully and skeptically, as if onboarding to the project for the first time.\n-  Assume no prior context beyond what is in the code.\n-  Be explicit about *why* something is a problem or risk.\n-  If something is ambiguous, call it out.\n-  If something looks intentional but questionable, note that too.\n\n**Output Requirements**\n-  Produce a **single Markdown file**.\n-  Save it to: `docs/reviews/`\n-  Filename format:  \n  `{YYYY-MM-DD_HH-MM}_[short-descriptive-review-title].md`\n-  Use clear Markdown structure, such as:\n  - Overview / Summary\n  - High-Priority Issues\n  - Medium / Low-Proority Issues\n  - Code Smells / Style Problems\n  - Questions or Unclear Intent\n  - Suggestions for Improvement\n\n**Tone**\n-  Direct, precise, and constructive.\n-  No fluff, no hedging.\n-  Treat this as a professional internal code review.\n\nBegin once the full codebase is available.",
        "keyword": ";cbr2"
      }
    }
  },
  "author": "polycast capture"
});
