// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-github-pull-request-template-ec6af1ae43",
  "title": "GitHub Pull Request Template",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"<!-- Thanks for opening a PR! Your contribution is much appreciated.-->\\n\\nFixes #\\n\\n## Proposed Changes\\n\\n  -\\n  -\\n  -\\n\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "<!-- Thanks for opening a PR! Your contribution is much appreciated.-->\n\nFixes #\n\n## Proposed Changes\n\n  -\n  -\n  -\n",
        "keyword": "!gh-pr"
      }
    }
  },
  "author": "polycast capture"
});
