// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-amplify-memory-extraction-987941127c",
  "title": "Amplify: Memory Extraction",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"System Prompt: \\\"You are a memory extraction expert. Extract key information from conversations.\\\"\\n\\nUser Prompt:\\nExtract key memories from this conversation that should be remembered for future interactions.\\nContext: {optional context like \\\"source:claude,session:abc-123\\\"}\\n\\nConversation:\\n{formatted messages with ROLE: content structure}\\n\\nExtract and return as JSON:\\n{\\n  \\\"memories\\\": [\\n    {\\n      \\\"type\\\": \\\"learning|decision|issue_solved|pattern|preference\\\",\\n      \\\"content\\\": \\\"concise memory content\\\",\\n      \\\"importance\\\": 0.0-1.0,\\n      \\\"tags\\\": [\\\"tag1\\\", \\\"tag2\\\"]\\n    }\\n  ],\\n  \\\"key_learnings\\\": [\\\"what was learned\\\"],\\n  \\\"decisions_made\\\": [\\\"decisions\\\"],\\n  \\\"issues_solved\\\": [\\\"problems resolved\\\"]\\n}\\n\\nFocus on technical decisions, problems solved, user preferences, and important patterns.\\nReturn ONLY valid JSON.\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "System Prompt: \"You are a memory extraction expert. Extract key information from conversations.\"\n\nUser Prompt:\nExtract key memories from this conversation that should be remembered for future interactions.\nContext: {optional context like \"source:claude,session:abc-123\"}\n\nConversation:\n{formatted messages with ROLE: content structure}\n\nExtract and return as JSON:\n{\n  \"memories\": [\n    {\n      \"type\": \"learning|decision|issue_solved|pattern|preference\",\n      \"content\": \"concise memory content\",\n      \"importance\": 0.0-1.0,\n      \"tags\": [\"tag1\", \"tag2\"]\n    }\n  ],\n  \"key_learnings\": [\"what was learned\"],\n  \"decisions_made\": [\"decisions\"],\n  \"issues_solved\": [\"problems resolved\"]\n}\n\nFocus on technical decisions, problems solved, user preferences, and important patterns.\nReturn ONLY valid JSON."
      }
    }
  },
  "author": "polycast capture"
});
