// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-loop-visual-regressions-until-match-deee3c07e7",
  "title": "Loop: Visual Regressions Until Match",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"Start the \\\"Visual Regression Until Match\\\" loop.\\nGoal: visual regression suite passes with intentional UI only\\nMax iterations: 6\\nBetween iterations run: npx playwright test --grep @visual\\nExit when: visual tests exit 0\\nStep 1: Run visual tests. Fix unintended UI diffs; update baselines only for deliberate design changes.\\nSelf-pace this loop. After each iteration, run the check command, read the output, and only continue if the exit condition is not met. Stop when the exit condition passes or max iterations is reached. Give a short status update each pass.\\nGuardrails (do not skip):\\n- Do not modify the check command or exit criteria to force success\\n- Do not skip, disable, or bypass checks to pass the exit condition\\n- If stuck after several iterations, stop and report blockers instead of gaming metrics\\n- Do not weaken, delete, or skip tests to make the suite pass\\n- Do not replace real assertions with trivial always-pass tests\\n- Prefer fixing production code over patching tests to go green\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "Start the \"Visual Regression Until Match\" loop.\nGoal: visual regression suite passes with intentional UI only\nMax iterations: 6\nBetween iterations run: npx playwright test --grep @visual\nExit when: visual tests exit 0\nStep 1: Run visual tests. Fix unintended UI diffs; update baselines only for deliberate design changes.\nSelf-pace this loop. After each iteration, run the check command, read the output, and only continue if the exit condition is not met. Stop when the exit condition passes or max iterations is reached. Give a short status update each pass.\nGuardrails (do not skip):\n- Do not modify the check command or exit criteria to force success\n- Do not skip, disable, or bypass checks to pass the exit condition\n- If stuck after several iterations, stop and report blockers instead of gaming metrics\n- Do not weaken, delete, or skip tests to make the suite pass\n- Do not replace real assertions with trivial always-pass tests\n- Prefer fixing production code over patching tests to go green"
      }
    }
  },
  "author": "polycast capture"
});
