// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-do-what-you-think-is-best-2c5b6a0962",
  "title": "do what you think is best.",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"Proceed. Do what you think is best.\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "Proceed. Do what you think is best.",
        "keyword": ";do"
      }
    }
  },
  "author": "polycast capture"
});
