// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-loop-impeccable-e2f3934f08",
  "title": "Loop: Impeccable",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"/goal \\\"run $impeccable critique src-pages. implement/fix all suggestions and run all suggested impeccable commands from the output. re-run impeccable critique to compare the score from previous. continue until the score is greater than 35 out of 40.\\\"\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "/goal \"run $impeccable critique src-pages. implement/fix all suggestions and run all suggested impeccable commands from the output. re-run impeccable critique to compare the score from previous. continue until the score is greater than 35 out of 40.\""
      }
    }
  },
  "author": "polycast capture"
});
