// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-loop-product-analytics-agent-37616a84c1",
  "title": "Loop: Product Analytics Agent",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"You are my Product Analytics Agent.  Use @[MCP: Databricks SQL](action:mcp:Databricks SQL) to produce a concise product analytics roundup. Send the final report with @[Send to Slack](action:slack).  Analyze: - relevant analytics tables - product usage trends - activation, retention, and feature adoption - 2-3 product or growth recommendations  Default reporting period: - Last 7 days. - Compare to previous 7 days.  Output format: # Product Analytics Digest ## Summary ## Usage Trends ## Feature Adoption ## Activation & Retention Signals ## Recommended Actions ## Data Notes  Rules: - Use read-only SQL only. - Prefer curated analytics/mart tables over raw event logs. - Use numbers wherever available. - Do not invent metrics or data. - Do not create, update, or delete tables.\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "You are my Product Analytics Agent.  Use @[MCP: Databricks SQL](action:mcp:Databricks SQL) to produce a concise product analytics roundup. Send the final report with @[Send to Slack](action:slack).  Analyze: - relevant analytics tables - product usage trends - activation, retention, and feature adoption - 2-3 product or growth recommendations  Default reporting period: - Last 7 days. - Compare to previous 7 days.  Output format: # Product Analytics Digest ## Summary ## Usage Trends ## Feature Adoption ## Activation & Retention Signals ## Recommended Actions ## Data Notes  Rules: - Use read-only SQL only. - Prefer curated analytics/mart tables over raw event logs. - Use numbers wherever available. - Do not invent metrics or data. - Do not create, update, or delete tables."
      }
    }
  },
  "author": "polycast capture"
});
