// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-git-diff-between-branches-with-exclusions-e53c301367",
  "title": "Git - Diff Between Branches (with exclusions)",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"git diff $(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')...$(git symbolic-ref --short HEAD) -- . \\\\\\n  ':(exclude)*.md' \\\\\\n  ':(exclude)*.json' \\\\\\n  ':(exclude)*.cursorrules' \\\\\\n  ':(exclude)*.windsurfrules' \\\\\\n  ':(exclude)*.log' \\\\\\n  ':(exclude)*.class' \\\\\\n  ':(exclude)*.tmp' \\\\\\n  ':(exclude)*.bak' \\\\\\n  ':(exclude)*~' \\\\\\n  ':(exclude)*.swp' \\\\\\n  ':(exclude)*.o' \\\\\\n  ':(exclude)*.obj' \\\\\\n  ':(exclude)*.dll' \\\\\\n  ':(exclude)*.exe' \\\\\\n  ':(exclude)node_modules/' \\\\\\n  ':(exclude).vscode/' \\\\\\n  ':(exclude).idea/' \\\\\\n  ':(exclude)*.sublime-*' \\\\\\n  ':(exclude)coverage/' \\\\\\n  ':(exclude)*.lcov' \\\\\\n  ':(exclude)docs/' \\\\\\n  ':(exclude)package-lock.json' \\\\\\n  ':(exclude)yarn.lock' \\\\\\n  ':(exclude)Pipfile.lock' \\\\\\n  ':(exclude).gitignore' \\\\\\n  ':(exclude).gitattributes' | pbcopy\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "git diff $(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')...$(git symbolic-ref --short HEAD) -- . \\\n  ':(exclude)*.md' \\\n  ':(exclude)*.json' \\\n  ':(exclude)*.cursorrules' \\\n  ':(exclude)*.windsurfrules' \\\n  ':(exclude)*.log' \\\n  ':(exclude)*.class' \\\n  ':(exclude)*.tmp' \\\n  ':(exclude)*.bak' \\\n  ':(exclude)*~' \\\n  ':(exclude)*.swp' \\\n  ':(exclude)*.o' \\\n  ':(exclude)*.obj' \\\n  ':(exclude)*.dll' \\\n  ':(exclude)*.exe' \\\n  ':(exclude)node_modules/' \\\n  ':(exclude).vscode/' \\\n  ':(exclude).idea/' \\\n  ':(exclude)*.sublime-*' \\\n  ':(exclude)coverage/' \\\n  ':(exclude)*.lcov' \\\n  ':(exclude)docs/' \\\n  ':(exclude)package-lock.json' \\\n  ':(exclude)yarn.lock' \\\n  ':(exclude)Pipfile.lock' \\\n  ':(exclude).gitignore' \\\n  ':(exclude).gitattributes' | pbcopy",
        "keyword": ";git:diff:branch"
      }
    }
  },
  "author": "polycast capture"
});
