// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-python-mcp-servers-d43a4e567e",
  "title": "Python MCP Servers",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"{\\n  \\\"mcpServers\\\": {\\n    \\\"python-sdk\\\": {\\n      \\\"name\\\": \\\"Python SDK\\\",\\n      \\\"command\\\": \\\"python\\\",\\n      \\\"args\\\": [\\n        \\\"-m\\\",\\n        \\\"python_sdk.server\\\"\\n      ],\\n      \\\"env\\\": {}\\n    },\\n    \\\"postgresql\\\": {\\n      \\\"name\\\": \\\"PostgreSQL MCP\\\",\\n      \\\"command\\\": \\\"python\\\",\\n      \\\"args\\\": [\\n        \\\"-m\\\",\\n        \\\"server_postgres\\\"\\n      ],\\n      \\\"env\\\": {\\n        \\\"DATABASE_URL\\\": \\\"postgresql://dallascrilley@localhost:5432/dev_db\\\"\\n      }\\n    },\\n    \\\"opik\\\": {\\n      \\\"name\\\": \\\"Opik MCP\\\",\\n      \\\"command\\\": \\\"python\\\",\\n      \\\"args\\\": [\\n        \\\"-m\\\",\\n        \\\"opik_mcp\\\"\\n      ],\\n      \\\"env\\\": {}\\n    },\\n    \\\"memory-bank\\\": {\\n      \\\"name\\\": \\\"Memory Bank MCP\\\",\\n      \\\"command\\\": \\\"server-memory\\\",\\n      \\\"args\\\": [],\\n      \\\"env\\\": {}\\n    },\\n    \\\"sequential-thinking\\\": {\\n      \\\"name\\\": \\\"Sequential Thinking MCP\\\",\\n      \\\"command\\\": \\\"code-reasoning\\\",\\n      \\\"args\\\": [],\\n      \\\"env\\\": {}\\n    },\\n    \\\"brave-search\\\": {\\n      \\\"name\\\": \\\"Brave Search MCP\\\",\\n      \\\"command\\\": \\\"server-brave-search\\\",\\n      \\\"args\\\": [],\\n      \\\"env\\\": {}\\n    },\\n    \\\"context7\\\": {\\n      \\\"type\\\": \\\"stdio\\\",\\n      \\\"command\\\": \\\"npx\\\",\\n      \\\"args\\\": [\\n        \\\"-y\\\",\\n        \\\"@upstash/context7-mcp\\\"\\n      ],\\n      \\\"env\\\": {}\\n    }\\n  }\\n}\\n\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "{\n  \"mcpServers\": {\n    \"python-sdk\": {\n      \"name\": \"Python SDK\",\n      \"command\": \"python\",\n      \"args\": [\n        \"-m\",\n        \"python_sdk.server\"\n      ],\n      \"env\": {}\n    },\n    \"postgresql\": {\n      \"name\": \"PostgreSQL MCP\",\n      \"command\": \"python\",\n      \"args\": [\n        \"-m\",\n        \"server_postgres\"\n      ],\n      \"env\": {\n        \"DATABASE_URL\": \"postgresql://dallascrilley@localhost:5432/dev_db\"\n      }\n    },\n    \"opik\": {\n      \"name\": \"Opik MCP\",\n      \"command\": \"python\",\n      \"args\": [\n        \"-m\",\n        \"opik_mcp\"\n      ],\n      \"env\": {}\n    },\n    \"memory-bank\": {\n      \"name\": \"Memory Bank MCP\",\n      \"command\": \"server-memory\",\n      \"args\": [],\n      \"env\": {}\n    },\n    \"sequential-thinking\": {\n      \"name\": \"Sequential Thinking MCP\",\n      \"command\": \"code-reasoning\",\n      \"args\": [],\n      \"env\": {}\n    },\n    \"brave-search\": {\n      \"name\": \"Brave Search MCP\",\n      \"command\": \"server-brave-search\",\n      \"args\": [],\n      \"env\": {}\n    },\n    \"context7\": {\n      \"type\": \"stdio\",\n      \"command\": \"npx\",\n      \"args\": [\n        \"-y\",\n        \"@upstash/context7-mcp\"\n      ],\n      \"env\": {}\n    }\n  }\n}\n"
      }
    }
  },
  "author": "polycast capture"
});
