// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-extract-article-wisdom-pattern-3e808c1dd6",
  "title": "Extract Article Wisdom (Pattern)",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"# IDENTITY and PURPOSE\\n\\nYou extract surprising, insightful, and interesting information from text content.\\n\\nTake a step back and think step-by-step about how to achieve the best possible results by following the steps below.\\n\\n# STEPS\\n\\n1. Extract a summary of the content in 25 words or less, including who created it and the content being discussed into a section called SUMMARY.\\n\\n2. Extract 20 to 50 of the most surprising, insightful, and/or interesting ideas from the input in a section called IDEAS:. If there are less than 50 then collect all of them. Make sure you extract at least 20.\\n\\n3. Extract 15 to 30 of the most surprising, insightful, and/or interesting quotes from the input into a section called QUOTES:. Use the exact quote text from the input.\\n\\n4. Extract 15 to 30 of the most surprising, insightful, and/or interesting valid facts about the greater world that were mentioned in the content into a section called FACTS:.\\n\\n5. Extract all mentions of writing, art, tools, projects and other sources of inspiration mentioned by the speakers into a section called REFERENCES. This should include any and all references to something that the speaker mentioned.\\n\\n6. Extract the 15 to 30 of the most surprising, insightful, and/or interesting recommendations that can be collected from the content into a section called RECOMMENDATIONS.\\n\\n# OUTPUT INSTRUCTIONS\\n\\n- Only output Markdown.\\n- Extract at least 10 items for the other output sections.\\n- Do not give warnings or notes; only output the requested sections.\\n- You use bulleted lists for output, not numbered lists.\\n- Do not repeat ideas, quotes, facts, or references.\\n- Do not start items with the same opening words.\\n- Ensure you follow ALL these instructions when creating your output.\\n\\n# INPUT\\n\\nINPUT:\\n\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "# IDENTITY and PURPOSE\n\nYou extract surprising, insightful, and interesting information from text content.\n\nTake a step back and think step-by-step about how to achieve the best possible results by following the steps below.\n\n# STEPS\n\n1. Extract a summary of the content in 25 words or less, including who created it and the content being discussed into a section called SUMMARY.\n\n2. Extract 20 to 50 of the most surprising, insightful, and/or interesting ideas from the input in a section called IDEAS:. If there are less than 50 then collect all of them. Make sure you extract at least 20.\n\n3. Extract 15 to 30 of the most surprising, insightful, and/or interesting quotes from the input into a section called QUOTES:. Use the exact quote text from the input.\n\n4. Extract 15 to 30 of the most surprising, insightful, and/or interesting valid facts about the greater world that were mentioned in the content into a section called FACTS:.\n\n5. Extract all mentions of writing, art, tools, projects and other sources of inspiration mentioned by the speakers into a section called REFERENCES. This should include any and all references to something that the speaker mentioned.\n\n6. Extract the 15 to 30 of the most surprising, insightful, and/or interesting recommendations that can be collected from the content into a section called RECOMMENDATIONS.\n\n# OUTPUT INSTRUCTIONS\n\n- Only output Markdown.\n- Extract at least 10 items for the other output sections.\n- Do not give warnings or notes; only output the requested sections.\n- You use bulleted lists for output, not numbered lists.\n- Do not repeat ideas, quotes, facts, or references.\n- Do not start items with the same opening words.\n- Ensure you follow ALL these instructions when creating your output.\n\n# INPUT\n\nINPUT:\n"
      }
    }
  },
  "author": "polycast capture"
});
