// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-use-code-reviewer-skill-62888f2678",
  "title": "Use Code-Reviewer skill",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"Use the requesting-code-review skill exactly as described in SKILL.md\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "Use the requesting-code-review skill exactly as described in SKILL.md"
      }
    }
  },
  "author": "polycast capture"
});
