// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-remotion-promo-best-practices-305fbad35c",
  "title": "Remotion: promo best practices",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"Use Remotion best practices skill. Create a 30-second video at 30fps. Start with a hook: white text on black background, 'Where do you even buy music anymore?' — fade it in, hold for 2 seconds, fade out.\\n\\nNext section: show the Disc Depot logo from public/discdepot-logo.png. Use a warm orange gradient background. Add a subtle tagline below: 'Music, delivered.’.\\n\\nIn the next section, add a counter that counts up to 12,000 with a plus sign. Label it 'Happy customers'. Keep the same background style.\\n\\nCreate 5 CD album covers as abstract gradient cards. Different color combinations. Animate them sliding in one by one, arranged in a row.\\n\\nAdd artist names and song titles.\\n\\nLet’s add a final section:\\nEnd with a call to action: 'Find your sound.' and the URL 'discdepot.com'. Fade to black.\\n\\nLet’s improve the transition between series. For example: orange in the second section should interpolate from black to orange. Now it’s just not too smooth. And improve that between sections.\\n\\n# A lot of refining prompts followed.\\n\\nVery nice! Can you make logo react to audio using `useAudioData` hook? https://www.remotion.dev/docs/use-windowed-audio-data.md\\n\\nCan you make ALL scenes audio reactive? So that all elements dance to the music frequencies?\\n\\nI want everything react to low frequencies only\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "Use Remotion best practices skill. Create a 30-second video at 30fps. Start with a hook: white text on black background, 'Where do you even buy music anymore?' — fade it in, hold for 2 seconds, fade out.\n\nNext section: show the Disc Depot logo from public/discdepot-logo.png. Use a warm orange gradient background. Add a subtle tagline below: 'Music, delivered.’.\n\nIn the next section, add a counter that counts up to 12,000 with a plus sign. Label it 'Happy customers'. Keep the same background style.\n\nCreate 5 CD album covers as abstract gradient cards. Different color combinations. Animate them sliding in one by one, arranged in a row.\n\nAdd artist names and song titles.\n\nLet’s add a final section:\nEnd with a call to action: 'Find your sound.' and the URL 'discdepot.com'. Fade to black.\n\nLet’s improve the transition between series. For example: orange in the second section should interpolate from black to orange. Now it’s just not too smooth. And improve that between sections.\n\n# A lot of refining prompts followed.\n\nVery nice! Can you make logo react to audio using `useAudioData` hook? https://www.remotion.dev/docs/use-windowed-audio-data.md\n\nCan you make ALL scenes audio reactive? So that all elements dance to the music frequencies?\n\nI want everything react to low frequencies only"
      }
    }
  },
  "author": "polycast capture"
});
