// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-audit-zshell-c0fb68f295",
  "title": "Audit Zshell",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"zsh -lixc 'exit' 2> /tmp/zsh-startup.trace\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "zsh -lixc 'exit' 2> /tmp/zsh-startup.trace"
      }
    }
  },
  "author": "polycast capture"
});
