// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-ai-provide-documentation-ef29783984",
  "title": "AI: Provide Documentation",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"Provide comprehensive documentation on the code provided. It should be very clear to any developer what the process flow, stack, important functions, files, methods, function call graph looks like, and any other relevant information that you would like to see if you were just starting to work on this project.\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "Provide comprehensive documentation on the code provided. It should be very clear to any developer what the process flow, stack, important functions, files, methods, function call graph looks like, and any other relevant information that you would like to see if you were just starting to work on this project."
      }
    }
  },
  "author": "polycast capture"
});
