// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-zen-precommit-695cf1f899",
  "title": "Zen: Precommit",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"Now use gemini and perform a review and precommit and ensure original requirements are met, no duplication of code or logic, no regressions or bugs introduced, high quality code, no smells, everything should work as expected\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "Now use gemini and perform a review and precommit and ensure original requirements are met, no duplication of code or logic, no regressions or bugs introduced, high quality code, no smells, everything should work as expected"
      }
    }
  },
  "author": "polycast capture"
});
