// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-putting-table-back-unicode-d15a210bd7",
  "title": "Putting Table Back Unicode",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"┳━┳ ヽ(ಠل͜ಠ)ﾉ\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "┳━┳ ヽ(ಠل͜ಠ)ﾉ",
        "keyword": "!putting-table"
      }
    }
  },
  "author": "polycast capture"
});
