// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-fresh-eyes-codebaze-review-612deda2b0",
  "title": "Fresh Eyes codebaze review",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"I want you to carefully read over this codebase with \\\"fresh eyes,\\\" looking super carefully for any obvious sloppiness, incomplete thoughts, logical errors, bugs, errors, problems, issues, confusion, etc. - output to docs/reviews folder as a markdown file with [date and time]_[unique review title].md\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "I want you to carefully read over this codebase with \"fresh eyes,\" looking super carefully for any obvious sloppiness, incomplete thoughts, logical errors, bugs, errors, problems, issues, confusion, etc. - output to docs/reviews folder as a markdown file with [date and time]_[unique review title].md",
        "keyword": ";cbr1"
      }
    }
  },
  "author": "polycast capture"
});
