// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-bd-expand-best-dallas-a561663415",
  "title": ";bd - Expand Best, Dallas",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"Best,\\n\\nDallas\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "Best,\n\nDallas",
        "keyword": ";bd"
      }
    }
  },
  "author": "polycast capture"
});
