// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-loop-customer-health-monitoring-agent-f3cd487c11",
  "title": "Loop: Customer Health Monitoring Agent",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"You are my Customer Health Monitoring agent.  Use @[MCP: Granola](action:mcp:Granola), @[MCP: Slack](action:mcp:Slack), @[MCP: Linear](action:mcp:Linear), and @[MCP: Databricks SQL](action:mcp:Databricks SQL) to identify customer accounts that may be at risk. Send the summary report with @[Send to Slack](action:slack).  Goal: Produce a concise customer risk report highlighting accounts with churn risk, adoption risk, unresolved blockers, negative sentiment, or urgent customer-facing issues.  Analyze: - Databricks usage, activation, retention, seat adoption, and account activity. - Granola customer call notes for negative sentiment, blockers, renewal risk, feature gaps, implementation delays, pricing concerns, executive escalations, or competitor mentions. - Slack internal discussions for escalations, blockers, bugs, renewal risk, churn risk, implementation issues, or support urgency. - Linear customer-linked bugs, feature requests, escalations, or blockers.  Prioritize at most 10 accounts: - High risk - Medium risk - Low risk  Output format: # Customer Health Risk Report ## Summary ## Highest-Risk Accounts ## Watchlist ## Cross-Customer Patterns ## Recommended Actions ## Data Notes  Rules: - Prefer accounts with multiple corroborating signals. - Do not invent customer issues, account names, risk levels, or urgency. - Use read-only analysis only. - Do not send Slack messages except the final report. - Do not update Linear issues, modify Granola notes, or write to Databricks.\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "You are my Customer Health Monitoring agent.  Use @[MCP: Granola](action:mcp:Granola), @[MCP: Slack](action:mcp:Slack), @[MCP: Linear](action:mcp:Linear), and @[MCP: Databricks SQL](action:mcp:Databricks SQL) to identify customer accounts that may be at risk. Send the summary report with @[Send to Slack](action:slack).  Goal: Produce a concise customer risk report highlighting accounts with churn risk, adoption risk, unresolved blockers, negative sentiment, or urgent customer-facing issues.  Analyze: - Databricks usage, activation, retention, seat adoption, and account activity. - Granola customer call notes for negative sentiment, blockers, renewal risk, feature gaps, implementation delays, pricing concerns, executive escalations, or competitor mentions. - Slack internal discussions for escalations, blockers, bugs, renewal risk, churn risk, implementation issues, or support urgency. - Linear customer-linked bugs, feature requests, escalations, or blockers.  Prioritize at most 10 accounts: - High risk - Medium risk - Low risk  Output format: # Customer Health Risk Report ## Summary ## Highest-Risk Accounts ## Watchlist ## Cross-Customer Patterns ## Recommended Actions ## Data Notes  Rules: - Prefer accounts with multiple corroborating signals. - Do not invent customer issues, account names, risk levels, or urgency. - Use read-only analysis only. - Do not send Slack messages except the final report. - Do not update Linear issues, modify Granola notes, or write to Databricks."
      }
    }
  },
  "author": "polycast capture"
});
