// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-jcs-goal-d592d92226",
  "title": "jcs goal",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"Goal: a frictionless, shareable-quality package — not “fewer error codes.” Stronger models only fix MODEL residuals; soup, ranking, and prep are PIPELINE and will survive a model upgrade.\\n\\nDestination (shared)\\nFull continuous path → private press page ready to share with clients or prospects:\\n\\nidentity · bio (when prep exists) · ranked clips + alternates · captions · campaign/social · blog · press page\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "Goal: a frictionless, shareable-quality package — not “fewer error codes.” Stronger models only fix MODEL residuals; soup, ranking, and prep are PIPELINE and will survive a model upgrade.\n\nDestination (shared)\nFull continuous path → private press page ready to share with clients or prospects:\n\nidentity · bio (when prep exists) · ranked clips + alternates · captions · campaign/social · blog · press page"
      }
    }
  },
  "author": "polycast capture"
});
