// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-sharper-vertical-mode-rncn-mac-235e1e49dd",
  "title": "Sharper Vertical Mode RNCN Mac",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"displayplacer \\\"id:2180AB77-D84F-4EB0-B8A7-7D2A25D76D99 mode:57\\\"\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "displayplacer \"id:2180AB77-D84F-4EB0-B8A7-7D2A25D76D99 mode:57\""
      }
    }
  },
  "author": "polycast capture"
});
