// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-commit-and-push-043894c4d4",
  "title": "Commit and push",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"Commit and push. For any existing dirty/unstaged/changed files, inspect them further. Plan a separate commit for any that are useful; either stash or discard the rest.\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "Commit and push. For any existing dirty/unstaged/changed files, inspect them further. Plan a separate commit for any that are useful; either stash or discard the rest.",
        "keyword": ";com"
      }
    }
  },
  "author": "polycast capture"
});
