// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-mkcp-create-directory-and-copy-file-into-it-78f2d32d15",
  "title": "mkcp - Create directory and copy file into it",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"mkcp \");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "mkcp ",
        "keyword": "mkcp"
      }
    }
  },
  "author": "polycast capture"
});
