// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-portkey-no-local-dev-1-3abeed680e",
  "title": "PORTKEY_NO_LOCAL_DEV=1",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"PORTKEY_NO_LOCAL_DEV=1\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "PORTKEY_NO_LOCAL_DEV=1"
      }
    }
  },
  "author": "polycast capture"
});
