// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-debug-and-fix-troubleshoot-agent-68e72360f1",
  "title": "Debug and Fix / Troubleshoot (agent)",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"Create a plan to fix the issues that you identified, then implement in full. Validate and provide proof commands of your success when you are done.\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "Create a plan to fix the issues that you identified, then implement in full. Validate and provide proof commands of your success when you are done.",
        "keyword": ";fix"
      }
    }
  },
  "author": "polycast capture"
});
