// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-shell-cd-to-dotfiles-172f20a383",
  "title": "Shell: cd to ~/.dotfiles",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"cd ~/.dotfiles\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "cd ~/.dotfiles",
        "keyword": ";dotfiles"
      }
    }
  },
  "author": "polycast capture"
});
