// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-remotion-cta-252704f60f",
  "title": "Remotion: CTA",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"use remotion best practices. this is our youtube channel: https://www.⁠youtube.⁠com/@⁠remotion_dev. use curl scrape youtube to find the avatar and the subscriber count. multiple subscriber counts appear on the page, find the right one. make a white lower third that slides in from the bottom center. show the name, subscriber count and avatar.  display a typical fixed width black youtube subscribe button that changes from \\\"Subscribe\\\" to \\\"Subscribed\\\". use a ease-out animation and for pressing in the button and a spring animation with a slight bounce once the button is released. fade out the lower third. render it as a transparent prores video.\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "use remotion best practices. this is our youtube channel: https://www.⁠youtube.⁠com/@⁠remotion_dev. use curl scrape youtube to find the avatar and the subscriber count. multiple subscriber counts appear on the page, find the right one. make a white lower third that slides in from the bottom center. show the name, subscriber count and avatar.  display a typical fixed width black youtube subscribe button that changes from \"Subscribe\" to \"Subscribed\". use a ease-out animation and for pressing in the button and a spring animation with a slight bounce once the button is released. fade out the lower third. render it as a transparent prores video."
      }
    }
  },
  "author": "polycast capture"
});
