// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-tears-of-joy-unicode-787cb0c003",
  "title": "Tears Of Joy Unicode",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"ಥ‿ಥ\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "ಥ‿ಥ",
        "keyword": "!tears-of-joy"
      }
    }
  },
  "author": "polycast capture"
});
