// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-sleep-promise-5bea0e5733",
  "title": "Sleep Promise",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"const sleep = (time = 3000) => new Promise (resolve => setTimeout (resolve, time));\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "const sleep = (time = 3000) => new Promise (resolve => setTimeout (resolve, time));",
        "keyword": "!sleep"
      }
    }
  },
  "author": "polycast capture"
});
