// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-validate-review-feedback-cbr-7443cdc5d6",
  "title": "Validate/review feedback cbr",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"Review the provided feedback on our code, located in docs/reviews. it will be the newest md file in that folder. \\n\\nFirst, review each item against our codebase to confirm or refute that it is accurate and valid feedback. You are allowed to disagree if it is incorrect or if you have an even better way.\\n\\nIf it is valid feedback, implement the changes and commit your fixes atomically (one for each issue raised). If it any are invalid suggestions, explain why (stale/false assumptions etc) and skip them.\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "Review the provided feedback on our code, located in docs/reviews. it will be the newest md file in that folder. \n\nFirst, review each item against our codebase to confirm or refute that it is accurate and valid feedback. You are allowed to disagree if it is incorrect or if you have an even better way.\n\nIf it is valid feedback, implement the changes and commit your fixes atomically (one for each issue raised). If it any are invalid suggestions, explain why (stale/false assumptions etc) and skip them.",
        "keyword": ";cbr3"
      }
    }
  },
  "author": "polycast capture"
});
