// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-proceed-ai-a931c7b476",
  "title": "Proceed (AI)",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"Proceed with your recommended next steps.\\n\\n\\t1.\\tAnalyze Impact – Research affected dependencies, potential breaking changes, and related modules.\\n\\t2.\\tDocument Findings – Summarize key codebase areas, risk level (low/medium/high), and required updates.\\n\\t3.\\tExecute Changes – Apply modifications maintaining code style, backward compatibility, and testing requirements.\\n\\t4.\\tValidate – Verify related code functionality, check for compiler/linter warnings, and confirm no orphaned dependencies.\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "Proceed with your recommended next steps.\n\n\t1.\tAnalyze Impact – Research affected dependencies, potential breaking changes, and related modules.\n\t2.\tDocument Findings – Summarize key codebase areas, risk level (low/medium/high), and required updates.\n\t3.\tExecute Changes – Apply modifications maintaining code style, backward compatibility, and testing requirements.\n\t4.\tValidate – Verify related code functionality, check for compiler/linter warnings, and confirm no orphaned dependencies."
      }
    }
  },
  "author": "polycast capture"
});
