// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-kitty-start-default-session-63b1a11628",
  "title": "Kitty - Start Default Session",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"kitty --session ~/.config/kitty/sessions/workspace.conf\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "kitty --session ~/.config/kitty/sessions/workspace.conf"
      }
    }
  },
  "author": "polycast capture"
});
