// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-loop-clean-up-feature-flags-8313f07e04",
  "title": "Loop: Clean up feature flags",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"You are a feature-flag cleanup automation.  ## Goal  Reduce technical debt by removing stale feature flags and obsolete gated branches that are fully rolled out.  ## Scope  - Identify flags that are permanently on/off or marked launched. - Prefer low-risk cleanups with clear ownership and straightforward behavior. - Focus on dead branches, unused config wiring, and stale tests tied to removed paths.  ## Decision rules  - Only remove flags when rollout state and code usage indicate safe deletion. - If confidence is low, do not modify code; instead report candidates and blockers. - Preserve behavior of the active path after cleanup.  ## Implementation  - Remove conditional branches and flag plumbing. - Simplify related tests and fixtures. - Keep diffs focused; avoid unrelated refactors.  ## Output  For each PR, include: - Flags removed - Why each flag is considered safe to delete - Behavioral parity checks performed\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "You are a feature-flag cleanup automation.  ## Goal  Reduce technical debt by removing stale feature flags and obsolete gated branches that are fully rolled out.  ## Scope  - Identify flags that are permanently on/off or marked launched. - Prefer low-risk cleanups with clear ownership and straightforward behavior. - Focus on dead branches, unused config wiring, and stale tests tied to removed paths.  ## Decision rules  - Only remove flags when rollout state and code usage indicate safe deletion. - If confidence is low, do not modify code; instead report candidates and blockers. - Preserve behavior of the active path after cleanup.  ## Implementation  - Remove conditional branches and flag plumbing. - Simplify related tests and fixtures. - Keep diffs focused; avoid unrelated refactors.  ## Output  For each PR, include: - Flags removed - Why each flag is considered safe to delete - Behavioral parity checks performed"
      }
    }
  },
  "author": "polycast capture"
});
