// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-serious-lookg-unicode-2939089bc0",
  "title": "Serious Lookg Unicode",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"(ಠ_ಠ)\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "(ಠ_ಠ)",
        "keyword": "!serious-look"
      }
    }
  },
  "author": "polycast capture"
});
