// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-mcp-inspector-4e6c565d76",
  "title": "MCP Inspector",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"npx @modelcontextprotocol/inspector --config ./config.json\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "npx @modelcontextprotocol/inspector --config ./config.json"
      }
    }
  },
  "author": "polycast capture"
});
