// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-las-expand-0aedd0c780",
  "title": ";las - Expand",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"Please see the attached PDF for a recap on what's included in our video podcasting services, as well as our pricing.\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "Please see the attached PDF for a recap on what's included in our video podcasting services, as well as our pricing.",
        "keyword": ";las1"
      }
    }
  },
  "author": "polycast capture"
});
