// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-orchestration-d7773f2880",
  "title": "orchestration",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"For each:\\n1. Use the ce-brainstorm skill to further refine the idea into clear feature requirements/spec and save it to docs/plans. For any questions/clarifying questions you would normally ask, think about it based on project context and decide for me by using your best judgment.\\n2. Design/mock a top-tier UI/UX user flow for the feature and add it to the spec\\n3. Create a plan to implement using the plan skill\\n4. Add to beads and linear (bootstrap/onboard the project into beads and linear if it has not been already first)\\nOnce complete, determine the best order to implement each plan for each idea and use the orchestrate/orca-cli skills to implement. \\nCheck the final result of each implementation by using dogfood / check it using orca-browser for top quality and refine until it is pixel-perfect and everything works correctly.\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "For each:\n1. Use the ce-brainstorm skill to further refine the idea into clear feature requirements/spec and save it to docs/plans. For any questions/clarifying questions you would normally ask, think about it based on project context and decide for me by using your best judgment.\n2. Design/mock a top-tier UI/UX user flow for the feature and add it to the spec\n3. Create a plan to implement using the plan skill\n4. Add to beads and linear (bootstrap/onboard the project into beads and linear if it has not been already first)\nOnce complete, determine the best order to implement each plan for each idea and use the orchestrate/orca-cli skills to implement. \nCheck the final result of each implementation by using dogfood / check it using orca-browser for top quality and refine until it is pixel-perfect and everything works correctly."
      }
    }
  },
  "author": "polycast capture"
});
