// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-cursor-agent-map-key-entry-points-fd25f97a91",
  "title": "Cursor-Agent - Map Key Entry Points",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"cursor-agent --print \\\\\\\"Map the project structure and identify key entry points.\\\\\\\"\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "cursor-agent --print \\\"Map the project structure and identify key entry points.\\\""
      }
    }
  },
  "author": "polycast capture"
});
