// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-loop-guardrails-learning-loop-72da59ac54",
  "title": "Loop: Guardrails Learning Loop",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"Start the \\\"Guardrails Learning Loop\\\" loop.\\nGoal: tests and lint pass without repeating prior failure patterns\\nMax iterations: 12\\nBetween iterations run: npm test && npm run lint\\nExit when: all checks pass\\nStep 1: Read .agents/guardrails.md, run checks, and if a failure repeats, add a sign before fixing.\\nSelf-pace this loop. After each iteration, run the check command, read the output, and only continue if the exit condition is not met. Stop when the exit condition passes or max iterations is reached. Give a short status update each pass.\\nGuardrails (do not skip):\\n- Do not modify the check command or exit criteria to force success\\n- Do not skip, disable, or bypass checks to pass the exit condition\\n- If stuck after several iterations, stop and report blockers instead of gaming metrics\\n\\n# .agents/guardrails.md\\nSigns from repeated failures. Read before every iteration.\\n## Signs\\n- Never commit without running tests first.\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "Start the \"Guardrails Learning Loop\" loop.\nGoal: tests and lint pass without repeating prior failure patterns\nMax iterations: 12\nBetween iterations run: npm test && npm run lint\nExit when: all checks pass\nStep 1: Read .agents/guardrails.md, run checks, and if a failure repeats, add a sign before fixing.\nSelf-pace this loop. After each iteration, run the check command, read the output, and only continue if the exit condition is not met. Stop when the exit condition passes or max iterations is reached. Give a short status update each pass.\nGuardrails (do not skip):\n- Do not modify the check command or exit criteria to force success\n- Do not skip, disable, or bypass checks to pass the exit condition\n- If stuck after several iterations, stop and report blockers instead of gaming metrics\n\n# .agents/guardrails.md\nSigns from repeated failures. Read before every iteration.\n## Signs\n- Never commit without running tests first."
      }
    }
  },
  "author": "polycast capture"
});
