// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-concrete-spec-469d57678c",
  "title": "Concrete Spec",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"Turn this into a concrete spec (schema + exact workflows + scripts) sized into PRs.\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "Turn this into a concrete spec (schema + exact workflows + scripts) sized into PRs."
      }
    }
  },
  "author": "polycast capture"
});
