// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-loop-desloppify-pass-eb5c2f04f9",
  "title": "Loop: Desloppify Pass",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"Start the \\\"De-Sloppify Pass\\\" loop.\\nGoal: recent changes are clean, minimal, and convention-aligned\\nMax iterations: 4\\nBetween iterations run: npm run lint && npm test\\nExit when: review finds no slop and checks pass\\nStep 1: Review the diff for debug code, dead branches, and naming issues. Fix them with minimal diffs.\\nSelf-pace this loop. After each iteration, run the check command, read the output, and only continue if the exit condition is not met. Stop when the exit condition passes or max iterations is reached. Give a short status update each pass.\\nGuardrails (do not skip):\\n- Do not modify the check command or exit criteria to force success\\n- Do not skip, disable, or bypass checks to pass the exit condition\\n- If stuck after several iterations, stop and report blockers instead of gaming metrics\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "Start the \"De-Sloppify Pass\" loop.\nGoal: recent changes are clean, minimal, and convention-aligned\nMax iterations: 4\nBetween iterations run: npm run lint && npm test\nExit when: review finds no slop and checks pass\nStep 1: Review the diff for debug code, dead branches, and naming issues. Fix them with minimal diffs.\nSelf-pace this loop. After each iteration, run the check command, read the output, and only continue if the exit condition is not met. Stop when the exit condition passes or max iterations is reached. Give a short status update each pass.\nGuardrails (do not skip):\n- Do not modify the check command or exit criteria to force success\n- Do not skip, disable, or bypass checks to pass the exit condition\n- If stuck after several iterations, stop and report blockers instead of gaming metrics"
      }
    }
  },
  "author": "polycast capture"
});
