// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-continue-autonomously-83c2b24ced",
  "title": "continue autonomously",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"Continue autonomously, using your best judgement based on the context of this session, the goals and priorities of the project, and your expertise.\\n\\nBe proactive and think like a product owner. Intuit what needs to be done to launch this successfully and do it. Do not stop to ask me for things that you are able to manage yourself. Complete the task in its entirety.\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "Continue autonomously, using your best judgement based on the context of this session, the goals and priorities of the project, and your expertise.\n\nBe proactive and think like a product owner. Intuit what needs to be done to launch this successfully and do it. Do not stop to ask me for things that you are able to manage yourself. Complete the task in its entirety.",
        "keyword": ";auto"
      }
    }
  },
  "author": "polycast capture"
});
