// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-next-steps-ai-9b741aef47",
  "title": "Next steps (AI)",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"What are your recommended next steps?\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "What are your recommended next steps?"
      }
    }
  },
  "author": "polycast capture"
});
