// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-merge-tmux-windows-9e05545098",
  "title": "merge tmux windows",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"cur=\\\"$(tmux display-message -p '#S')\\\" && tmux list-windows -a -F '#S:#I' | awk -F: -v cur=\\\"$cur\\\" '$1!=cur{print}' | while IFS= read -r w; do tmux move-window -s \\\"$w\\\" -t \\\"${cur}:\\\"; done\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "cur=\"$(tmux display-message -p '#S')\" && tmux list-windows -a -F '#S:#I' | awk -F: -v cur=\"$cur\" '$1!=cur{print}' | while IFS= read -r w; do tmux move-window -s \"$w\" -t \"${cur}:\"; done"
      }
    }
  },
  "author": "polycast capture"
});
