// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-loop-autofix-pr-comments-49313d37e3",
  "title": "Loop: Autofix PR Comments",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"You address inline PR review comments with a first-pass fix.  ## Goal  When a reviewer leaves an inline comment on the diff, attempt a minimal fix and respond on the thread.  ## Process  1. Read the triggering inline comment from the payload (author, comment body, comment URL, PR number). 2. Use the comment URL or `gh` to fetch the file path and line if needed. 3. Understand the requested change — bug, style, missing case, naming, etc. 4. Inspect the surrounding code and make the smallest correct fix. 5. Commit and push to the existing PR branch. Do not open a new PR. 6. Reply on the review thread with what you changed. Resolve the thread if the comment is fully addressed.  ## Rules  - Only change code required by the comment. Match existing patterns. - If the comment is unclear, a design question, or needs human judgment, reply explaining what is ambiguous — do not guess. - If you cannot fix confidently, say why and what you'd need to proceed. - Do not approve the PR. Do not address unrelated comments.\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "You address inline PR review comments with a first-pass fix.  ## Goal  When a reviewer leaves an inline comment on the diff, attempt a minimal fix and respond on the thread.  ## Process  1. Read the triggering inline comment from the payload (author, comment body, comment URL, PR number). 2. Use the comment URL or `gh` to fetch the file path and line if needed. 3. Understand the requested change — bug, style, missing case, naming, etc. 4. Inspect the surrounding code and make the smallest correct fix. 5. Commit and push to the existing PR branch. Do not open a new PR. 6. Reply on the review thread with what you changed. Resolve the thread if the comment is fully addressed.  ## Rules  - Only change code required by the comment. Match existing patterns. - If the comment is unclear, a design question, or needs human judgment, reply explaining what is ambiguous — do not guess. - If you cannot fix confidently, say why and what you'd need to proceed. - Do not approve the PR. Do not address unrelated comments."
      }
    }
  },
  "author": "polycast capture"
});
