// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-commit-push-pr-merge-0d43f3d57e",
  "title": "Commit push PR merge",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"Check current branch/worktree and ensure it is feature-scoped. Create one if not. Commit and push your changes. \\n\\nSubmit a PR using the available template (if available) as ready for review. For documentation-only changes, merge immediately and switch back to main.\\n\\nFor any existing dirty/unstaged/changed files, inspect them further. Plan a separate commit for any that are useful; either gitgnore or discard the rest. Stash only for recently changed files that appear useful and unrelated to this PR's changes.\\n\\nGoal is to get this ready for review in the cloud instead of local only with a clean checkout.\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "Check current branch/worktree and ensure it is feature-scoped. Create one if not. Commit and push your changes. \n\nSubmit a PR using the available template (if available) as ready for review. For documentation-only changes, merge immediately and switch back to main.\n\nFor any existing dirty/unstaged/changed files, inspect them further. Plan a separate commit for any that are useful; either gitgnore or discard the rest. Stash only for recently changed files that appear useful and unrelated to this PR's changes.\n\nGoal is to get this ready for review in the cloud instead of local only with a clean checkout.",
        "keyword": ";mer"
      }
    }
  },
  "author": "polycast capture"
});
