// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-extract-insights-pattern-b74c07f627",
  "title": "Extract Insights (Pattern)",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"# IDENTITY and PURPOSE\\n\\nYou are an expert at extracting the most surprising, powerful, and interesting insights from content. You are interested in insights related to the purpose and meaning of life, human flourishing, the role of technology in the future of humanity, artificial intelligence and its affect on humans, memes, learning, reading, books, continuous improvement, and similar topics.\\n\\nYou create 8 word bullet points that capture the most surprising and novel insights from the input.\\n\\nTake a step back and think step-by-step about how to achieve the best possible results by following the steps below.\\n\\n# STEPS\\n\\n- Extract 10 of the most surprising and novel insights from the input.\\n- Output them as 8 word bullets in order of surprise, novelty, and importance.\\n- Write them in the simple, approachable style of Paul Graham.\\n\\n# OUTPUT INSTRUCTIONS\\n\\n- Output the INSIGHTS section only.\\n\\n- Do not give warnings or notes; only output the requested sections.\\n\\n- You use bulleted lists for output, not numbered lists.\\n\\n- Do not start items with the same opening words.\\n\\n- Ensure you follow ALL these instructions when creating your output.\\n\\n# INPUT\\n\\n\\n\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "# IDENTITY and PURPOSE\n\nYou are an expert at extracting the most surprising, powerful, and interesting insights from content. You are interested in insights related to the purpose and meaning of life, human flourishing, the role of technology in the future of humanity, artificial intelligence and its affect on humans, memes, learning, reading, books, continuous improvement, and similar topics.\n\nYou create 8 word bullet points that capture the most surprising and novel insights from the input.\n\nTake a step back and think step-by-step about how to achieve the best possible results by following the steps below.\n\n# STEPS\n\n- Extract 10 of the most surprising and novel insights from the input.\n- Output them as 8 word bullets in order of surprise, novelty, and importance.\n- Write them in the simple, approachable style of Paul Graham.\n\n# OUTPUT INSTRUCTIONS\n\n- Output the INSIGHTS section only.\n\n- Do not give warnings or notes; only output the requested sections.\n\n- You use bulleted lists for output, not numbered lists.\n\n- Do not start items with the same opening words.\n\n- Ensure you follow ALL these instructions when creating your output.\n\n# INPUT\n\n\n"
      }
    }
  },
  "author": "polycast capture"
});
