// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-github-issue-template-cd8bee0810",
  "title": "GitHub Issue Template",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"## Expected Behavior\\n\\n## Actual Behavior\\n\\n## Steps to Reproduce the Problem\\n\\n  1.\\n  1.\\n  1.\\n\\n## Specifications\\n\\n  - Version:\\n  - Platform:\\n  - Subsystem:\\n\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "## Expected Behavior\n\n## Actual Behavior\n\n## Steps to Reproduce the Problem\n\n  1.\n  1.\n  1.\n\n## Specifications\n\n  - Version:\n  - Platform:\n  - Subsystem:\n",
        "keyword": "!gh-issue"
      }
    }
  },
  "author": "polycast capture"
});
