// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-retouch-edit-ai-headshot-109eb4a454",
  "title": "retouch / edit ai headshot",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"Edit this portrait for a YouTube thumbnail while preserving the person’s exact identity and natural appearance.\\n\\nKeep the person’s facial structure, hairstyle, clothing, pose, expression, age, ethnicity, and proportions the same. No background changes.\\n\\nMake the portrait look more polished, confident, and thumbnail-ready, while remaining realistic.\\n\\nEnhance the image with professional headshot retouching:\\n- Brighten the face and eyes enough that the subject reads clearly at thumbnail size.\\n- Add moderate but natural contrast and clarity to the face.\\n- Clean up skin tone, shine, redness, under-eye darkness, and small blemishes while preserving pores, natural lines, freckles, facial hair, and real texture.\\n- Sharpen the eyes, brows, hair, lips, and facial edges enough to read clearly at thumbnail size, but avoid a crunchy or AI-enhanced look.\\n- Add subtle eye catchlights and make the eyes feel more awake, without changing eye shape or color.\\n- Use light dodge and burn to add dimension: brighten the forehead, cheeks, nose bridge, and under-eye area slightly; gently define the jawline, cheekbones, and hairline.\\n- Preserve realistic skin color and natural lighting.\\n- Keep the result appropriate for a professional podcast/interview YouTube thumbnail.\\n\\nGender-aware retouching:\\n- For men, prioritize natural texture, eye sharpness, beard/stubble detail, jaw definition, and confident contrast. Avoid glam smoothing.\\n- For women, prioritize even skin tone, soft but realistic texture cleanup, refined eyes/brows/lashes, clean hair detail, and natural polish. Avoid beauty-filter smoothing or facial reshaping.\\n\\nRestrictions:\\nNo stylization. No face reshaping. No slimming. No age reduction. No heavy makeup. No plastic skin. No altered expression. No background replacement. No artificial glamour look. Preserve identity above all else.\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "Edit this portrait for a YouTube thumbnail while preserving the person’s exact identity and natural appearance.\n\nKeep the person’s facial structure, hairstyle, clothing, pose, expression, age, ethnicity, and proportions the same. No background changes.\n\nMake the portrait look more polished, confident, and thumbnail-ready, while remaining realistic.\n\nEnhance the image with professional headshot retouching:\n- Brighten the face and eyes enough that the subject reads clearly at thumbnail size.\n- Add moderate but natural contrast and clarity to the face.\n- Clean up skin tone, shine, redness, under-eye darkness, and small blemishes while preserving pores, natural lines, freckles, facial hair, and real texture.\n- Sharpen the eyes, brows, hair, lips, and facial edges enough to read clearly at thumbnail size, but avoid a crunchy or AI-enhanced look.\n- Add subtle eye catchlights and make the eyes feel more awake, without changing eye shape or color.\n- Use light dodge and burn to add dimension: brighten the forehead, cheeks, nose bridge, and under-eye area slightly; gently define the jawline, cheekbones, and hairline.\n- Preserve realistic skin color and natural lighting.\n- Keep the result appropriate for a professional podcast/interview YouTube thumbnail.\n\nGender-aware retouching:\n- For men, prioritize natural texture, eye sharpness, beard/stubble detail, jaw definition, and confident contrast. Avoid glam smoothing.\n- For women, prioritize even skin tone, soft but realistic texture cleanup, refined eyes/brows/lashes, clean hair detail, and natural polish. Avoid beauty-filter smoothing or facial reshaping.\n\nRestrictions:\nNo stylization. No face reshaping. No slimming. No age reduction. No heavy makeup. No plastic skin. No altered expression. No background replacement. No artificial glamour look. Preserve identity above all else."
      }
    }
  },
  "author": "polycast capture"
});
