// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-loop-docs-sync-after-edit-3414cf5f59",
  "title": "Loop: Docs Sync After Edit",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"Start the \\\"Docs Sync After Edits\\\" loop.\\nGoal: documentation matches the current code changes\\nMax iterations: 3\\nBetween iterations run: git diff main...HEAD --name-only\\nExit when: all affected docs are updated and verified\\nStep 1: Review the diff, find stale docs, update them, and verify accuracy.\\nSelf-pace this loop. After each iteration, run the check command, read the output, and only continue if the exit condition is not met. Stop when the exit condition passes or max iterations is reached. Give a short status update each pass.\\nGuardrails (do not skip):\\n- Do not modify the check command or exit criteria to force success\\n- Do not skip, disable, or bypass checks to pass the exit condition\\n- If stuck after several iterations, stop and report blockers instead of gaming metrics\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "Start the \"Docs Sync After Edits\" loop.\nGoal: documentation matches the current code changes\nMax iterations: 3\nBetween iterations run: git diff main...HEAD --name-only\nExit when: all affected docs are updated and verified\nStep 1: Review the diff, find stale docs, update them, and verify accuracy.\nSelf-pace this loop. After each iteration, run the check command, read the output, and only continue if the exit condition is not met. Stop when the exit condition passes or max iterations is reached. Give a short status update each pass.\nGuardrails (do not skip):\n- Do not modify the check command or exit criteria to force success\n- Do not skip, disable, or bypass checks to pass the exit condition\n- If stuck after several iterations, stop and report blockers instead of gaming metrics"
      }
    }
  },
  "author": "polycast capture"
});
