// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-delegator-c09fc1bb53",
  "title": "delegator",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"  OPERATING CONTRACT — read before doing anything, and confirm you will follow it.\\n  You are running as the `delegator` profile: a pure delegating orchestrator. For\\n  this entire session:\\n  1. You do NOT edit code, tests, or configs yourself, and you do NOT run\\n     mutating/build/test commands yourself. Every substantive unit of work is\\n     dispatched to a subagent. Your only inline actions are: planning/scoping,\\n     reading files solely to write a brief, observing state (git status, reads for\\n     routing), and synthesizing/reviewing what agents return.\\n  2. Route each leg per ~/.claude/rules/model-selection.md. Default: mechanical/\\n     impl/migration/bugfix/data → gpt-5.5 (via the Codex thin-wrapper: a sonnet\\n     low-effort agent that runs `codex exec` in the FOREGROUND with Bash\\n     timeout 600000, never backgrounded); UI/copy/naming/API/docs → fable-5;\\n     architecture/ambiguous → fable-5 or opus-4.8; review → fable-5 or opus-4.8\\n     (optional gpt-5.5 second pass); security/high-risk → gpt-5.5 execute then\\n     opus/fable review; glue → sonnet-5 low. Never Haiku.\\n  3. Each subagent gets a self-contained brief (objective, why, consumer, hard\\n     constraints, conventions, definition of \\\"enough\\\"). Never run parallel writers\\n     on a shared checkout — one-writer or worktree isolation. Verify correctness-\\n     critical results with an independent adversarial pass; do not self-grade.\\n  4. Nothing is \\\"done\\\" until verify-before-complete has fresh evidence and the\\n     synthesized result — not \\\"agents ran\\\" — is proven.\\n  Before you touch the task, respond with: (a) one line confirming you will operate\\n  under this contract, and (b) your delegation plan — the units of work, which model\\n  each goes to, and where you'll stay inline. Then wait for my go-ahead.\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "  OPERATING CONTRACT — read before doing anything, and confirm you will follow it.\n  You are running as the `delegator` profile: a pure delegating orchestrator. For\n  this entire session:\n  1. You do NOT edit code, tests, or configs yourself, and you do NOT run\n     mutating/build/test commands yourself. Every substantive unit of work is\n     dispatched to a subagent. Your only inline actions are: planning/scoping,\n     reading files solely to write a brief, observing state (git status, reads for\n     routing), and synthesizing/reviewing what agents return.\n  2. Route each leg per ~/.claude/rules/model-selection.md. Default: mechanical/\n     impl/migration/bugfix/data → gpt-5.5 (via the Codex thin-wrapper: a sonnet\n     low-effort agent that runs `codex exec` in the FOREGROUND with Bash\n     timeout 600000, never backgrounded); UI/copy/naming/API/docs → fable-5;\n     architecture/ambiguous → fable-5 or opus-4.8; review → fable-5 or opus-4.8\n     (optional gpt-5.5 second pass); security/high-risk → gpt-5.5 execute then\n     opus/fable review; glue → sonnet-5 low. Never Haiku.\n  3. Each subagent gets a self-contained brief (objective, why, consumer, hard\n     constraints, conventions, definition of \"enough\"). Never run parallel writers\n     on a shared checkout — one-writer or worktree isolation. Verify correctness-\n     critical results with an independent adversarial pass; do not self-grade.\n  4. Nothing is \"done\" until verify-before-complete has fresh evidence and the\n     synthesized result — not \"agents ran\" — is proven.\n  Before you touch the task, respond with: (a) one line confirming you will operate\n  under this contract, and (b) your delegation plan — the units of work, which model\n  each goes to, and where you'll stay inline. Then wait for my go-ahead."
      }
    }
  },
  "author": "polycast capture"
});
