// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-fresh-eyes-c9e9601023",
  "title": "Fresh Eyes",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"Great, now I want you to carefully read over all of the new code you just wrote and other existing code you just modified with \\\"fresh eyes,\\\" looking super carefully for any obvious sloppiness, incomplete thoughts, logical errors, bugs, errors, problems, issues, confusion, etc.\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "Great, now I want you to carefully read over all of the new code you just wrote and other existing code you just modified with \"fresh eyes,\" looking super carefully for any obvious sloppiness, incomplete thoughts, logical errors, bugs, errors, problems, issues, confusion, etc.",
        "keyword": ";fr"
      }
    }
  },
  "author": "polycast capture"
});
