// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-prime-ai-a11375d322",
  "title": "Prime (AI)",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"Prime your context before we begin.\\n\\nGoal: Prime the conversation by establishing comprehensive project context through systematic code and documentation review.\\n\\nProcess\\n\\n1. Documentation Review (Foundation)\\n\\nStart by reading:\\n\\n\\t•\\t﻿README.md﻿ — Project overview, purpose, setup instructions\\n\\t•\\t﻿agents.md﻿ or ﻿claude.md﻿ — AI agent behaviors, capabilities, and guidelines\\n\\t•\\t﻿ARCHITECTURE.md﻿ or similar — System design and key concepts (if exists)\\n\\n\\n2. Repository State Analysis (Current Status)\\n\\nExamine:\\n\\n\\t•\\tRecent commits — What changed and why (last 5-10 commits)\\n\\t•\\tOpen issues — Known problems, feature requests, blockers\\n\\t•\\tStaged files — Work in progress\\n\\t•\\tUnstaged changes — Recent modifications not yet committed\\n\\n3. Codebase Exploration (Priority-Based)\\n\\nExplore the most important folders/files in this order:\\n\\n\\t•\\tEntry points (﻿main.py﻿, ﻿index.js﻿, ﻿app.tsx﻿, etc.)\\n\\t•\\tConfiguration files (﻿.env﻿, ﻿config/﻿, ﻿setup.py﻿, ﻿package.json﻿)\\n\\t•\\tCore modules — Business logic and primary functionality\\n\\t•\\tTests — Understanding expected behavior\\n\\t•\\tType definitions — For statically-typed projects\\n\\n4. Context Synthesis (Ready to Assist)\\n\\nConsolidate findings into a mental model of:\\n\\n\\t•\\tProject scope and technology stack\\n\\t•\\tCurrent priorities and pain points\\n\\t•\\tDevelopment patterns and conventions\\n\\t•\\tKnown limitations or technical debt\\n\\nOutput Format\\n\\nProvide a brief summary highlighting:\\n\\n\\t•\\t✅ What the project does\\n\\t•\\t📊 Current state (active work, issues)\\n\\t•\\t🔧 Tech stack and key patterns\\n\\t•\\t⚠️ Notable constraints or priorities\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "Prime your context before we begin.\n\nGoal: Prime the conversation by establishing comprehensive project context through systematic code and documentation review.\n\nProcess\n\n1. Documentation Review (Foundation)\n\nStart by reading:\n\n\t•\t﻿README.md﻿ — Project overview, purpose, setup instructions\n\t•\t﻿agents.md﻿ or ﻿claude.md﻿ — AI agent behaviors, capabilities, and guidelines\n\t•\t﻿ARCHITECTURE.md﻿ or similar — System design and key concepts (if exists)\n\n\n2. Repository State Analysis (Current Status)\n\nExamine:\n\n\t•\tRecent commits — What changed and why (last 5-10 commits)\n\t•\tOpen issues — Known problems, feature requests, blockers\n\t•\tStaged files — Work in progress\n\t•\tUnstaged changes — Recent modifications not yet committed\n\n3. Codebase Exploration (Priority-Based)\n\nExplore the most important folders/files in this order:\n\n\t•\tEntry points (﻿main.py﻿, ﻿index.js﻿, ﻿app.tsx﻿, etc.)\n\t•\tConfiguration files (﻿.env﻿, ﻿config/﻿, ﻿setup.py﻿, ﻿package.json﻿)\n\t•\tCore modules — Business logic and primary functionality\n\t•\tTests — Understanding expected behavior\n\t•\tType definitions — For statically-typed projects\n\n4. Context Synthesis (Ready to Assist)\n\nConsolidate findings into a mental model of:\n\n\t•\tProject scope and technology stack\n\t•\tCurrent priorities and pain points\n\t•\tDevelopment patterns and conventions\n\t•\tKnown limitations or technical debt\n\nOutput Format\n\nProvide a brief summary highlighting:\n\n\t•\t✅ What the project does\n\t•\t📊 Current state (active work, issues)\n\t•\t🔧 Tech stack and key patterns\n\t•\t⚠️ Notable constraints or priorities"
      }
    }
  },
  "author": "polycast capture"
});
