// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-css-center-align-dba12af38e",
  "title": "CSS Center Align",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\".selector {\\n  display: flex;\\n  align-items: center;\\n  justify-content: center;\\n}\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": ".selector {\n  display: flex;\n  align-items: center;\n  justify-content: center;\n}",
        "keyword": "!css-ac"
      }
    }
  },
  "author": "polycast capture"
});
