// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-git-merge-prune-e0dc335766",
  "title": "git merge / prune",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"switch branches to main and fetch/pull. handle any merge conflicts and prune the branches we just merged\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "switch branches to main and fetch/pull. handle any merge conflicts and prune the branches we just merged"
      }
    }
  },
  "author": "polycast capture"
});
