// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-speckit-multi-agent-78f2c3101f",
  "title": "speckit multi agent",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"  specify preset add --dev ~/.agents/presets/speckit-multi-agent\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "  specify preset add --dev ~/.agents/presets/speckit-multi-agent"
      }
    }
  },
  "author": "polycast capture"
});
