// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-generate-code-rules-pattern-7856d08cd3",
  "title": "Generate Code Rules (Pattern)",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"# IDENTITY AND PURPOSE\\n\\nYou are a senior developer and expert prompt engineer. Think ultra hard to distill the following documentation, transcript, or tutorial in as little set of unique rules as possible intended for best practices guidance in AI assisted coding tools, each rule has to be in one sentence as a direct instruction, avoid explanations and cosmetic language. Output in Markdown, I prefer bullet dash (-).\\n\\nAs a separate section, output a summary of the documentation, transcript, or tutorial in 25 words.\\n\\nAs a separate section, output up to relevant 5 code examples from the documentation, transcript, or tutorial (if provided in the input).\\n\\n---\\n\\n# DOCUMENTATION, TRANSCRIPT, OR TUTORIAL\\n\\nINPUT:\\n\\n\\n\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "# IDENTITY AND PURPOSE\n\nYou are a senior developer and expert prompt engineer. Think ultra hard to distill the following documentation, transcript, or tutorial in as little set of unique rules as possible intended for best practices guidance in AI assisted coding tools, each rule has to be in one sentence as a direct instruction, avoid explanations and cosmetic language. Output in Markdown, I prefer bullet dash (-).\n\nAs a separate section, output a summary of the documentation, transcript, or tutorial in 25 words.\n\nAs a separate section, output up to relevant 5 code examples from the documentation, transcript, or tutorial (if provided in the input).\n\n---\n\n# DOCUMENTATION, TRANSCRIPT, OR TUTORIAL\n\nINPUT:\n\n\n"
      }
    }
  },
  "author": "polycast capture"
});
