// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-validation-review-31bd3ffcfd",
  "title": "Validation -> Review",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"Validation → PR → Review Workflow\\n\\n  For each validation phase:\\n\\n  1. **Fix until green**\\n     Run `./scripts/validate/run.sh` repeatedly, fixing errors until all validations pass.\\n\\n  2. **Submit PR**\\n     Create a PR with your fixes for that phase.\\n\\n  3. **Wait for CI**\\n     Monitor PR checks until all pass.\\n\\n  4. **Address review feedback**\\n     Run `reviewrover {PR #}` to fetch comments. Implement all relevant feedback (one review round only).\\n\\n  5. **Final self-review**\\n     Before merging, review the PR yourself with fresh eyes. Fix any logical errors, oversights, or inconsistencies.\\n\\n  6. **Merge and continue**\\n     Merge the PR, then return to step 1 for the next validation phase.\\n\\n  Repeat until all validation phases pass.\\n\\n  Key changes:\\n  - Numbered steps instead of run-on sentences\\n  - Explicit \\\"one review round only\\\" placement\\n  - Clear loop structure (per-phase, not nested)\\n  - Separated CI waiting from review feedback\\n  - \\\"Fresh eyes\\\" review placed right before merge decision\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "Validation → PR → Review Workflow\n\n  For each validation phase:\n\n  1. **Fix until green**\n     Run `./scripts/validate/run.sh` repeatedly, fixing errors until all validations pass.\n\n  2. **Submit PR**\n     Create a PR with your fixes for that phase.\n\n  3. **Wait for CI**\n     Monitor PR checks until all pass.\n\n  4. **Address review feedback**\n     Run `reviewrover {PR #}` to fetch comments. Implement all relevant feedback (one review round only).\n\n  5. **Final self-review**\n     Before merging, review the PR yourself with fresh eyes. Fix any logical errors, oversights, or inconsistencies.\n\n  6. **Merge and continue**\n     Merge the PR, then return to step 1 for the next validation phase.\n\n  Repeat until all validation phases pass.\n\n  Key changes:\n  - Numbered steps instead of run-on sentences\n  - Explicit \"one review round only\" placement\n  - Clear loop structure (per-phase, not nested)\n  - Separated CI waiting from review feedback\n  - \"Fresh eyes\" review placed right before merge decision"
      }
    }
  },
  "author": "polycast capture"
});
