// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-ai-archive-summarize-conversation-aaaf5b8505",
  "title": "AI: Archive/Summarize Conversation",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"You are to act as a diligent AI archivist. Your primary task is to meticulously review our entire conversation history and generate a concise summary titled \\\"Conversation Summary for Context.\\\"\\n\\nThe purpose of this summary is to create a compact and efficient context block that can be used to bootstrap future conversations. It must retain all critical information for seamless continuity while aggressively minimizing the token count.\\n\\n**Content Priorities (Include and distill the following):**\\n*   **Core Objectives:** What are the primary, overarching goals we have established?\\n*   **Key Tasks & Requests:** What specific tasks have I asked you to perform? Emphasize the most recent and ongoing tasks.\\n*   **Standing Instructions & Preferences:** What constraints, style guides, formats, or personal preferences have I instructed you to follow in your responses?\\n*   **Crucial Outcomes & Decisions:** What key information has been generated, or what specific decisions have we made that will inform future work?\\n\\n**Exclusion Criteria (Omit the following):**\\n*   Conversational filler, greetings, and pleasantries.\\n*   Redundant information, corrected misunderstandings, or dead-end exploratory paths.\\n*   The full text of long outputs (e.g., code, articles), unless the final version itself is the critical context. Summarize the output's purpose or outcome instead.\\n\\n**Output Format:**\\n*   Begin the entire output with the heading: `## Conversation Summary for Context`\\n*   Use a clear, scannable format, such as nested bullet points under the priority headings listed above.\\n*   Be factual, objective, and extremely concise.\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "You are to act as a diligent AI archivist. Your primary task is to meticulously review our entire conversation history and generate a concise summary titled \"Conversation Summary for Context.\"\n\nThe purpose of this summary is to create a compact and efficient context block that can be used to bootstrap future conversations. It must retain all critical information for seamless continuity while aggressively minimizing the token count.\n\n**Content Priorities (Include and distill the following):**\n*   **Core Objectives:** What are the primary, overarching goals we have established?\n*   **Key Tasks & Requests:** What specific tasks have I asked you to perform? Emphasize the most recent and ongoing tasks.\n*   **Standing Instructions & Preferences:** What constraints, style guides, formats, or personal preferences have I instructed you to follow in your responses?\n*   **Crucial Outcomes & Decisions:** What key information has been generated, or what specific decisions have we made that will inform future work?\n\n**Exclusion Criteria (Omit the following):**\n*   Conversational filler, greetings, and pleasantries.\n*   Redundant information, corrected misunderstandings, or dead-end exploratory paths.\n*   The full text of long outputs (e.g., code, articles), unless the final version itself is the critical context. Summarize the output's purpose or outcome instead.\n\n**Output Format:**\n*   Begin the entire output with the heading: `## Conversation Summary for Context`\n*   Use a clear, scannable format, such as nested bullet points under the priority headings listed above.\n*   Be factual, objective, and extremely concise.",
        "keyword": ";archive_conv"
      }
    }
  },
  "author": "polycast capture"
});
