// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-mcp-sequential-thinking-519067d146",
  "title": "MCP: Sequential Thinking",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"claude mcp add sequential-thinking npx -- -y @modelcontextprotocol/server-sequential-thinking --scope user\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "claude mcp add sequential-thinking npx -- -y @modelcontextprotocol/server-sequential-thinking --scope user"
      }
    }
  },
  "author": "polycast capture"
});
