// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-loveto-expand-we-d-love-to-work-with-db2e420d77",
  "title": ";loveto - Expand - we'd love to work with",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"We'd love to work with you on starting your own show!\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "We'd love to work with you on starting your own show!"
      }
    }
  },
  "author": "polycast capture"
});
