// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-proceed-b943e0a94b",
  "title": "Proceed",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"Proceed/continue with the next best set of actions, using your best judgement to resolve any ambiguities or blockers that would prevent you from progressing. Reference bd board(s) and tasks as needed.\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "Proceed/continue with the next best set of actions, using your best judgement to resolve any ambiguities or blockers that would prevent you from progressing. Reference bd board(s) and tasks as needed.",
        "keyword": ";p"
      }
    }
  },
  "author": "polycast capture"
});
