// Generated by `polycast capture --from raycast-snippets`.
// The source export stays outside Git. Regenerate this file instead of editing it.

import { defineCommand } from "../../src/define.ts";

export default defineCommand({
  "id": "raycast-snippet-what-s-next-rule-74945652f8",
  "title": "What’s next rule",
  "description": "Static text captured from a Raycast snippet export.",
  "modality": "none",
  "body": {
    "lang": "node",
    "source": "process.stdout.write(\"Future Horizon Rule\\n\\nWhen asked what to work on next, do not stop at the immediate next task.\\n\\nAlways reason from the project's defined finish line backward.\\n\\nProvide:\\n- Finish line definition\\n- Current completion estimate\\n- Remaining milestones to reach completion\\n- Critical path\\n- Parallelizable work\\n- Top 3 immediate tasks\\n- Next 10 tasks\\n- Major milestones beyond those tasks\\n\\nPrefer roadmap thinking over todo-list thinking.\\nOptimize for shortest path to project completion, not merely the next available task.\");"
  },
  "targets": [
    "raycast-snippet"
  ],
  "x": {
    "raycast": {
      "snippet": {
        "text": "Future Horizon Rule\n\nWhen asked what to work on next, do not stop at the immediate next task.\n\nAlways reason from the project's defined finish line backward.\n\nProvide:\n- Finish line definition\n- Current completion estimate\n- Remaining milestones to reach completion\n- Critical path\n- Parallelizable work\n- Top 3 immediate tasks\n- Next 10 tasks\n- Major milestones beyond those tasks\n\nPrefer roadmap thinking over todo-list thinking.\nOptimize for shortest path to project completion, not merely the next available task.",
        "keyword": ";wn"
      }
    }
  },
  "author": "polycast capture"
});
